// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type Post struct {
	ID        string           `db:"id" json:"id"`
	UserID    string           `db:"user_id" json:"user_id"`
	Title     string           `db:"title" json:"title"`
	Content   string           `db:"content" json:"content"`
	Slug      string           `db:"slug" json:"slug"`
	Published *bool            `db:"published" json:"published"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Product struct {
	ID           pgtype.UUID         `db:"id" json:"id"`
	SupplierID   pgtype.UUID         `db:"supplier_id" json:"supplier_id"`
	Sku          string              `db:"sku" json:"sku"`
	Name         string              `db:"name" json:"name"`
	NameZh       *string             `db:"name_zh" json:"name_zh"`
	Category     string              `db:"category" json:"category"`
	Specs        []byte              `db:"specs" json:"specs"`
	PriceUsd     pgtype.Numeric      `db:"price_usd" json:"price_usd"`
	Moq          *int32              `db:"moq" json:"moq"`
	StockQty     *int32              `db:"stock_qty" json:"stock_qty"`
	LeadTimeDays *int32              `db:"lead_time_days" json:"lead_time_days"`
	DatasheetUrl *string             `db:"datasheet_url" json:"datasheet_url"`
	Embedding    *pgvector_go.Vector `db:"embedding" json:"embedding"`
	CreatedAt    pgtype.Timestamptz  `db:"created_at" json:"created_at"`
}

type Quote struct {
	ID             string             `db:"id" json:"id"`
	RfqID          string             `db:"rfq_id" json:"rfq_id"`
	SupplierID     pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	ProductID      pgtype.UUID        `db:"product_id" json:"product_id"`
	PriceUsd       pgtype.Numeric     `db:"price_usd" json:"price_usd"`
	LeadTimeDays   *int32             `db:"lead_time_days" json:"lead_time_days"`
	ValidityDate   pgtype.Date        `db:"validity_date" json:"validity_date"`
	SupplierNotes  *string            `db:"supplier_notes" json:"supplier_notes"`
	MatchScore     *int32             `db:"match_score" json:"match_score"`
	Status         string             `db:"status" json:"status"`
	SubmittedAt    pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ManufacturerID pgtype.UUID        `db:"manufacturer_id" json:"manufacturer_id"`
}

type Rfq struct {
	ID                string             `db:"id" json:"id"`
	BuyerID           string             `db:"buyer_id" json:"buyer_id"`
	QueryText         string             `db:"query_text" json:"query_text"`
	ParsedSpecs       []byte             `db:"parsed_specs" json:"parsed_specs"`
	MatchedProductIds []pgtype.UUID      `db:"matched_product_ids" json:"matched_product_ids"`
	Status            string             `db:"status" json:"status"`
	Qty               *int32             `db:"qty" json:"qty"`
	TargetDate        pgtype.Date        `db:"target_date" json:"target_date"`
	ShippingAddress   *string            `db:"shipping_address" json:"shipping_address"`
	Notes             *string            `db:"notes" json:"notes"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	BuyerEmail        *string            `db:"buyer_email" json:"buyer_email"`
	BuyerCompany      *string            `db:"buyer_company" json:"buyer_company"`
	ProjectID         *string            `db:"project_id" json:"project_id"`
}

type Supplier struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Name           string             `db:"name" json:"name"`
	NameZh         *string            `db:"name_zh" json:"name_zh"`
	City           string             `db:"city" json:"city"`
	Country        string             `db:"country" json:"country"`
	Cluster        *string            `db:"cluster" json:"cluster"`
	Capabilities   []string           `db:"capabilities" json:"capabilities"`
	Certifications []string           `db:"certifications" json:"certifications"`
	FoundedYear    *int32             `db:"founded_year" json:"founded_year"`
	Employees      *int32             `db:"employees" json:"employees"`
	FacilitySizeM2 *int32             `db:"facility_size_m2" json:"facility_size_m2"`
	AnnualOutput   *string            `db:"annual_output" json:"annual_output"`
	OnTimeRate     pgtype.Numeric     `db:"on_time_rate" json:"on_time_rate"`
	Rating         pgtype.Numeric     `db:"rating" json:"rating"`
	OrderCount     int32              `db:"order_count" json:"order_count"`
	VerifiedAt     pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	AuditReportUrl *string            `db:"audit_report_url" json:"audit_report_url"`
	PhotoUrl       *string            `db:"photo_url" json:"photo_url"`
	ContactEmail   *string            `db:"contact_email" json:"contact_email"`
	ContactWechat  *string            `db:"contact_wechat" json:"contact_wechat"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SupplierApplication struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Payload   []byte             `db:"payload" json:"payload"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
