// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    supplier_id, sku, name, name_zh, category, specs,
    price_usd, moq, stock_qty, lead_time_days, datasheet_url
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
RETURNING id, supplier_id, sku, name, name_zh, category, specs, price_usd, moq, stock_qty, lead_time_days, datasheet_url, embedding, created_at
`

type CreateProductParams struct {
	SupplierID   pgtype.UUID    `db:"supplier_id" json:"supplier_id"`
	Sku          string         `db:"sku" json:"sku"`
	Name         string         `db:"name" json:"name"`
	NameZh       *string        `db:"name_zh" json:"name_zh"`
	Category     string         `db:"category" json:"category"`
	Specs        []byte         `db:"specs" json:"specs"`
	PriceUsd     pgtype.Numeric `db:"price_usd" json:"price_usd"`
	Moq          *int32         `db:"moq" json:"moq"`
	StockQty     *int32         `db:"stock_qty" json:"stock_qty"`
	LeadTimeDays *int32         `db:"lead_time_days" json:"lead_time_days"`
	DatasheetUrl *string        `db:"datasheet_url" json:"datasheet_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.SupplierID,
		arg.Sku,
		arg.Name,
		arg.NameZh,
		arg.Category,
		arg.Specs,
		arg.PriceUsd,
		arg.Moq,
		arg.StockQty,
		arg.LeadTimeDays,
		arg.DatasheetUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Sku,
		&i.Name,
		&i.NameZh,
		&i.Category,
		&i.Specs,
		&i.PriceUsd,
		&i.Moq,
		&i.StockQty,
		&i.LeadTimeDays,
		&i.DatasheetUrl,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, supplier_id, sku, name, name_zh, category, specs, price_usd, moq, stock_qty, lead_time_days, datasheet_url, embedding, created_at FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Sku,
		&i.Name,
		&i.NameZh,
		&i.Category,
		&i.Specs,
		&i.PriceUsd,
		&i.Moq,
		&i.StockQty,
		&i.LeadTimeDays,
		&i.DatasheetUrl,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const getProductBySupplierSKU = `-- name: GetProductBySupplierSKU :one
SELECT id, supplier_id, sku, name, name_zh, category, specs, price_usd, moq, stock_qty, lead_time_days, datasheet_url, embedding, created_at FROM products WHERE supplier_id = $1 AND sku = $2 LIMIT 1
`

type GetProductBySupplierSKUParams struct {
	SupplierID pgtype.UUID `db:"supplier_id" json:"supplier_id"`
	Sku        string      `db:"sku" json:"sku"`
}

func (q *Queries) GetProductBySupplierSKU(ctx context.Context, arg GetProductBySupplierSKUParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySupplierSKU, arg.SupplierID, arg.Sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Sku,
		&i.Name,
		&i.NameZh,
		&i.Category,
		&i.Specs,
		&i.PriceUsd,
		&i.Moq,
		&i.StockQty,
		&i.LeadTimeDays,
		&i.DatasheetUrl,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const listProductsBySupplier = `-- name: ListProductsBySupplier :many
SELECT id, supplier_id, sku, name, name_zh, category, specs, price_usd, moq, stock_qty, lead_time_days, datasheet_url, embedding, created_at FROM products
WHERE supplier_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsBySupplierParams struct {
	SupplierID pgtype.UUID `db:"supplier_id" json:"supplier_id"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListProductsBySupplier(ctx context.Context, arg ListProductsBySupplierParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsBySupplier, arg.SupplierID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.Sku,
			&i.Name,
			&i.NameZh,
			&i.Category,
			&i.Specs,
			&i.PriceUsd,
			&i.Moq,
			&i.StockQty,
			&i.LeadTimeDays,
			&i.DatasheetUrl,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsMissingEmbedding = `-- name: ListProductsMissingEmbedding :many
SELECT id, supplier_id, sku, name, name_zh, category, specs, price_usd, moq, stock_qty, lead_time_days, datasheet_url, embedding, created_at FROM products
WHERE embedding IS NULL
ORDER BY created_at ASC
LIMIT $1
`

// Used by cmd/embed CLI to find products that still need an embedding.
func (q *Queries) ListProductsMissingEmbedding(ctx context.Context, limit int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsMissingEmbedding, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.Sku,
			&i.Name,
			&i.NameZh,
			&i.Category,
			&i.Specs,
			&i.PriceUsd,
			&i.Moq,
			&i.StockQty,
			&i.LeadTimeDays,
			&i.DatasheetUrl,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsMissingEmbeddingWithSupplier = `-- name: ListProductsMissingEmbeddingWithSupplier :many
SELECT
    p.id, p.supplier_id, p.sku, p.name, p.name_zh, p.category, p.specs,
    p.price_usd, p.moq, p.stock_qty, p.lead_time_days, p.datasheet_url,
    p.embedding, p.created_at,
    s.name    AS supplier_name,
    s.name_zh AS supplier_name_zh,
    s.city    AS supplier_city,
    s.cluster AS supplier_cluster
FROM products p
JOIN suppliers s ON s.id = p.supplier_id
WHERE p.embedding IS NULL
ORDER BY p.created_at ASC
LIMIT $1
`

type ListProductsMissingEmbeddingWithSupplierRow struct {
	ID              pgtype.UUID         `db:"id" json:"id"`
	SupplierID      pgtype.UUID         `db:"supplier_id" json:"supplier_id"`
	Sku             string              `db:"sku" json:"sku"`
	Name            string              `db:"name" json:"name"`
	NameZh          *string             `db:"name_zh" json:"name_zh"`
	Category        string              `db:"category" json:"category"`
	Specs           []byte              `db:"specs" json:"specs"`
	PriceUsd        pgtype.Numeric      `db:"price_usd" json:"price_usd"`
	Moq             *int32              `db:"moq" json:"moq"`
	StockQty        *int32              `db:"stock_qty" json:"stock_qty"`
	LeadTimeDays    *int32              `db:"lead_time_days" json:"lead_time_days"`
	DatasheetUrl    *string             `db:"datasheet_url" json:"datasheet_url"`
	Embedding       *pgvector_go.Vector `db:"embedding" json:"embedding"`
	CreatedAt       pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	SupplierName    string              `db:"supplier_name" json:"supplier_name"`
	SupplierNameZh  *string             `db:"supplier_name_zh" json:"supplier_name_zh"`
	SupplierCity    string              `db:"supplier_city" json:"supplier_city"`
	SupplierCluster *string             `db:"supplier_cluster" json:"supplier_cluster"`
}

// Same as above, but joins the supplier so the embedding-text builder has
// everything it needs (supplier name, city, cluster) without an N+1 lookup.
func (q *Queries) ListProductsMissingEmbeddingWithSupplier(ctx context.Context, limit int32) ([]ListProductsMissingEmbeddingWithSupplierRow, error) {
	rows, err := q.db.Query(ctx, listProductsMissingEmbeddingWithSupplier, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsMissingEmbeddingWithSupplierRow{}
	for rows.Next() {
		var i ListProductsMissingEmbeddingWithSupplierRow
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.Sku,
			&i.Name,
			&i.NameZh,
			&i.Category,
			&i.Specs,
			&i.PriceUsd,
			&i.Moq,
			&i.StockQty,
			&i.LeadTimeDays,
			&i.DatasheetUrl,
			&i.Embedding,
			&i.CreatedAt,
			&i.SupplierName,
			&i.SupplierNameZh,
			&i.SupplierCity,
			&i.SupplierCluster,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductEmbedding = `-- name: UpdateProductEmbedding :exec
UPDATE products
SET embedding = $2
WHERE id = $1
`

type UpdateProductEmbeddingParams struct {
	ID        pgtype.UUID         `db:"id" json:"id"`
	Embedding *pgvector_go.Vector `db:"embedding" json:"embedding"`
}

func (q *Queries) UpdateProductEmbedding(ctx context.Context, arg UpdateProductEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateProductEmbedding, arg.ID, arg.Embedding)
	return err
}

const upsertProduct = `-- name: UpsertProduct :one
INSERT INTO products (
    supplier_id, sku, name, name_zh, category, specs,
    price_usd, moq, stock_qty, lead_time_days, datasheet_url
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
ON CONFLICT (supplier_id, sku) DO UPDATE SET
    name           = EXCLUDED.name,
    name_zh        = EXCLUDED.name_zh,
    category       = EXCLUDED.category,
    specs          = EXCLUDED.specs,
    price_usd      = EXCLUDED.price_usd,
    moq            = EXCLUDED.moq,
    stock_qty      = EXCLUDED.stock_qty,
    lead_time_days = EXCLUDED.lead_time_days,
    datasheet_url  = EXCLUDED.datasheet_url
RETURNING id, supplier_id, sku, name, name_zh, category, specs, price_usd, moq, stock_qty, lead_time_days, datasheet_url, embedding, created_at
`

type UpsertProductParams struct {
	SupplierID   pgtype.UUID    `db:"supplier_id" json:"supplier_id"`
	Sku          string         `db:"sku" json:"sku"`
	Name         string         `db:"name" json:"name"`
	NameZh       *string        `db:"name_zh" json:"name_zh"`
	Category     string         `db:"category" json:"category"`
	Specs        []byte         `db:"specs" json:"specs"`
	PriceUsd     pgtype.Numeric `db:"price_usd" json:"price_usd"`
	Moq          *int32         `db:"moq" json:"moq"`
	StockQty     *int32         `db:"stock_qty" json:"stock_qty"`
	LeadTimeDays *int32         `db:"lead_time_days" json:"lead_time_days"`
	DatasheetUrl *string        `db:"datasheet_url" json:"datasheet_url"`
}

// Idempotent on (supplier_id, sku); seed re-runs UPDATE in place. The existing
// embedding is preserved on conflict so re-seeding doesn't invalidate the
// already-computed vector (which is expensive to regenerate).
func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, upsertProduct,
		arg.SupplierID,
		arg.Sku,
		arg.Name,
		arg.NameZh,
		arg.Category,
		arg.Specs,
		arg.PriceUsd,
		arg.Moq,
		arg.StockQty,
		arg.LeadTimeDays,
		arg.DatasheetUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.Sku,
		&i.Name,
		&i.NameZh,
		&i.Category,
		&i.Specs,
		&i.PriceUsd,
		&i.Moq,
		&i.StockQty,
		&i.LeadTimeDays,
		&i.DatasheetUrl,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}
