// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountSuppliers(ctx context.Context, arg CountSuppliersParams) (int32, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error)
	GetProductBySupplierSKU(ctx context.Context, arg GetProductBySupplierSKUParams) (Product, error)
	GetSupplierByID(ctx context.Context, id pgtype.UUID) (Supplier, error)
	GetSupplierByName(ctx context.Context, name string) (Supplier, error)
	ListProductsBySupplier(ctx context.Context, arg ListProductsBySupplierParams) ([]Product, error)
	// Used by cmd/embed CLI to find products that still need an embedding.
	ListProductsMissingEmbedding(ctx context.Context, limit int32) ([]Product, error)
	// Same as above, but joins the supplier so the embedding-text builder has
	// everything it needs (supplier name, city, cluster) without an N+1 lookup.
	ListProductsMissingEmbeddingWithSupplier(ctx context.Context, limit int32) ([]ListProductsMissingEmbeddingWithSupplierRow, error)
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	UpdateProductEmbedding(ctx context.Context, arg UpdateProductEmbeddingParams) error
	// Idempotent on (supplier_id, sku); seed re-runs UPDATE in place. The existing
	// embedding is preserved on conflict so re-seeding doesn't invalidate the
	// already-computed vector (which is expensive to regenerate).
	UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error)
	// Idempotent insert used by the seed CLI. Caller supplies a deterministic id
	// (uuid5 of supplier slug); re-runs UPDATE the row in place rather than
	// duplicating rows. order_count is preserved on UPDATE so seeding doesn't
	// clobber live counters.
	UpsertSupplier(ctx context.Context, arg UpsertSupplierParams) (Supplier, error)
}

var _ Querier = (*Queries)(nil)
