// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quotes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingQuote = `-- name: CreatePendingQuote :one
INSERT INTO quotes (id, rfq_id, supplier_id, product_id, match_score, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id, rfq_id, supplier_id, product_id, price_usd, lead_time_days, validity_date, supplier_notes, match_score, status, submitted_at, created_at
`

type CreatePendingQuoteParams struct {
	ID         string      `db:"id" json:"id"`
	RfqID      string      `db:"rfq_id" json:"rfq_id"`
	SupplierID pgtype.UUID `db:"supplier_id" json:"supplier_id"`
	ProductID  pgtype.UUID `db:"product_id" json:"product_id"`
	MatchScore *int32      `db:"match_score" json:"match_score"`
}

func (q *Queries) CreatePendingQuote(ctx context.Context, arg CreatePendingQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, createPendingQuote,
		arg.ID,
		arg.RfqID,
		arg.SupplierID,
		arg.ProductID,
		arg.MatchScore,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.RfqID,
		&i.SupplierID,
		&i.ProductID,
		&i.PriceUsd,
		&i.LeadTimeDays,
		&i.ValidityDate,
		&i.SupplierNotes,
		&i.MatchScore,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getQuoteForSupplier = `-- name: GetQuoteForSupplier :one
SELECT id, rfq_id, supplier_id, product_id, price_usd, lead_time_days, validity_date, supplier_notes, match_score, status, submitted_at, created_at FROM quotes
WHERE rfq_id = $1 AND supplier_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetQuoteForSupplierParams struct {
	RfqID      string      `db:"rfq_id" json:"rfq_id"`
	SupplierID pgtype.UUID `db:"supplier_id" json:"supplier_id"`
}

func (q *Queries) GetQuoteForSupplier(ctx context.Context, arg GetQuoteForSupplierParams) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuoteForSupplier, arg.RfqID, arg.SupplierID)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.RfqID,
		&i.SupplierID,
		&i.ProductID,
		&i.PriceUsd,
		&i.LeadTimeDays,
		&i.ValidityDate,
		&i.SupplierNotes,
		&i.MatchScore,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listQuotesForRFQ = `-- name: ListQuotesForRFQ :many
SELECT id, rfq_id, supplier_id, product_id, price_usd, lead_time_days, validity_date, supplier_notes, match_score, status, submitted_at, created_at FROM quotes
WHERE rfq_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListQuotesForRFQ(ctx context.Context, rfqID string) ([]Quote, error) {
	rows, err := q.db.Query(ctx, listQuotesForRFQ, rfqID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quote{}
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.RfqID,
			&i.SupplierID,
			&i.ProductID,
			&i.PriceUsd,
			&i.LeadTimeDays,
			&i.ValidityDate,
			&i.SupplierNotes,
			&i.MatchScore,
			&i.Status,
			&i.SubmittedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextQuoteSeq = `-- name: NextQuoteSeq :one
SELECT nextval('quote_id_seq')::bigint
`

func (q *Queries) NextQuoteSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextQuoteSeq)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const submitQuote = `-- name: SubmitQuote :one
UPDATE quotes
SET price_usd      = $3,
    lead_time_days = $4,
    validity_date  = $5,
    supplier_notes = $6,
    status         = 'submitted',
    submitted_at   = now()
WHERE rfq_id = $1 AND supplier_id = $2 AND status = 'pending'
RETURNING id, rfq_id, supplier_id, product_id, price_usd, lead_time_days, validity_date, supplier_notes, match_score, status, submitted_at, created_at
`

type SubmitQuoteParams struct {
	RfqID         string         `db:"rfq_id" json:"rfq_id"`
	SupplierID    pgtype.UUID    `db:"supplier_id" json:"supplier_id"`
	PriceUsd      pgtype.Numeric `db:"price_usd" json:"price_usd"`
	LeadTimeDays  *int32         `db:"lead_time_days" json:"lead_time_days"`
	ValidityDate  pgtype.Date    `db:"validity_date" json:"validity_date"`
	SupplierNotes *string        `db:"supplier_notes" json:"supplier_notes"`
}

// The pending row was created with the RFQ; submission fills in commercial
// terms. Guarding on status = 'pending' makes re-submission a no-rows error
// instead of silently overwriting an accepted/rejected quote.
func (q *Queries) SubmitQuote(ctx context.Context, arg SubmitQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, submitQuote,
		arg.RfqID,
		arg.SupplierID,
		arg.PriceUsd,
		arg.LeadTimeDays,
		arg.ValidityDate,
		arg.SupplierNotes,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.RfqID,
		&i.SupplierID,
		&i.ProductID,
		&i.PriceUsd,
		&i.LeadTimeDays,
		&i.ValidityDate,
		&i.SupplierNotes,
		&i.MatchScore,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}
