// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rfqs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRFQsByBuyer = `-- name: CountRFQsByBuyer :one
SELECT COUNT(*)::int FROM rfqs
WHERE buyer_id = $1
  AND ($2::text IS NULL OR status = $2::text)
`

type CountRFQsByBuyerParams struct {
	BuyerID string  `db:"buyer_id" json:"buyer_id"`
	Status  *string `db:"status" json:"status"`
}

func (q *Queries) CountRFQsByBuyer(ctx context.Context, arg CountRFQsByBuyerParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRFQsByBuyer, arg.BuyerID, arg.Status)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createRFQ = `-- name: CreateRFQ :one
INSERT INTO rfqs (
    id, buyer_id, buyer_email, buyer_company,
    query_text, parsed_specs, matched_product_ids,
    status, qty, target_date, shipping_address, notes
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11, $12
)
RETURNING id, buyer_id, query_text, parsed_specs, matched_product_ids, status, qty, target_date, shipping_address, notes, created_at, buyer_email, buyer_company
`

type CreateRFQParams struct {
	ID                string        `db:"id" json:"id"`
	BuyerID           string        `db:"buyer_id" json:"buyer_id"`
	BuyerEmail        *string       `db:"buyer_email" json:"buyer_email"`
	BuyerCompany      *string       `db:"buyer_company" json:"buyer_company"`
	QueryText         string        `db:"query_text" json:"query_text"`
	ParsedSpecs       []byte        `db:"parsed_specs" json:"parsed_specs"`
	MatchedProductIds []pgtype.UUID `db:"matched_product_ids" json:"matched_product_ids"`
	Status            string        `db:"status" json:"status"`
	Qty               *int32        `db:"qty" json:"qty"`
	TargetDate        pgtype.Date   `db:"target_date" json:"target_date"`
	ShippingAddress   *string       `db:"shipping_address" json:"shipping_address"`
	Notes             *string       `db:"notes" json:"notes"`
}

func (q *Queries) CreateRFQ(ctx context.Context, arg CreateRFQParams) (Rfq, error) {
	row := q.db.QueryRow(ctx, createRFQ,
		arg.ID,
		arg.BuyerID,
		arg.BuyerEmail,
		arg.BuyerCompany,
		arg.QueryText,
		arg.ParsedSpecs,
		arg.MatchedProductIds,
		arg.Status,
		arg.Qty,
		arg.TargetDate,
		arg.ShippingAddress,
		arg.Notes,
	)
	var i Rfq
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.QueryText,
		&i.ParsedSpecs,
		&i.MatchedProductIds,
		&i.Status,
		&i.Qty,
		&i.TargetDate,
		&i.ShippingAddress,
		&i.Notes,
		&i.CreatedAt,
		&i.BuyerEmail,
		&i.BuyerCompany,
	)
	return i, err
}

const getRFQByID = `-- name: GetRFQByID :one
SELECT id, buyer_id, query_text, parsed_specs, matched_product_ids, status, qty, target_date, shipping_address, notes, created_at, buyer_email, buyer_company FROM rfqs WHERE id = $1
`

func (q *Queries) GetRFQByID(ctx context.Context, id string) (Rfq, error) {
	row := q.db.QueryRow(ctx, getRFQByID, id)
	var i Rfq
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.QueryText,
		&i.ParsedSpecs,
		&i.MatchedProductIds,
		&i.Status,
		&i.Qty,
		&i.TargetDate,
		&i.ShippingAddress,
		&i.Notes,
		&i.CreatedAt,
		&i.BuyerEmail,
		&i.BuyerCompany,
	)
	return i, err
}

const listProductsByIDs = `-- name: ListProductsByIDs :many
SELECT p.id, p.supplier_id, p.sku, p.name, p.name_zh, p.category,
       p.specs, p.price_usd, p.moq, p.stock_qty, p.lead_time_days, p.datasheet_url
FROM products p
WHERE p.id = ANY($1::uuid[])
`

type ListProductsByIDsRow struct {
	ID           pgtype.UUID    `db:"id" json:"id"`
	SupplierID   pgtype.UUID    `db:"supplier_id" json:"supplier_id"`
	Sku          string         `db:"sku" json:"sku"`
	Name         string         `db:"name" json:"name"`
	NameZh       *string        `db:"name_zh" json:"name_zh"`
	Category     string         `db:"category" json:"category"`
	Specs        []byte         `db:"specs" json:"specs"`
	PriceUsd     pgtype.Numeric `db:"price_usd" json:"price_usd"`
	Moq          *int32         `db:"moq" json:"moq"`
	StockQty     *int32         `db:"stock_qty" json:"stock_qty"`
	LeadTimeDays *int32         `db:"lead_time_days" json:"lead_time_days"`
	DatasheetUrl *string        `db:"datasheet_url" json:"datasheet_url"`
}

func (q *Queries) ListProductsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListProductsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listProductsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByIDsRow{}
	for rows.Next() {
		var i ListProductsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.Sku,
			&i.Name,
			&i.NameZh,
			&i.Category,
			&i.Specs,
			&i.PriceUsd,
			&i.Moq,
			&i.StockQty,
			&i.LeadTimeDays,
			&i.DatasheetUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRFQsByBuyer = `-- name: ListRFQsByBuyer :many
SELECT id, buyer_id, query_text, parsed_specs, matched_product_ids, status, qty, target_date, shipping_address, notes, created_at, buyer_email, buyer_company FROM rfqs
WHERE buyer_id = $1
  AND ($4::text IS NULL OR status = $4::text)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRFQsByBuyerParams struct {
	BuyerID string  `db:"buyer_id" json:"buyer_id"`
	Limit   int32   `db:"limit" json:"limit"`
	Offset  int32   `db:"offset" json:"offset"`
	Status  *string `db:"status" json:"status"`
}

func (q *Queries) ListRFQsByBuyer(ctx context.Context, arg ListRFQsByBuyerParams) ([]Rfq, error) {
	rows, err := q.db.Query(ctx, listRFQsByBuyer,
		arg.BuyerID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rfq{}
	for rows.Next() {
		var i Rfq
		if err := rows.Scan(
			&i.ID,
			&i.BuyerID,
			&i.QueryText,
			&i.ParsedSpecs,
			&i.MatchedProductIds,
			&i.Status,
			&i.Qty,
			&i.TargetDate,
			&i.ShippingAddress,
			&i.Notes,
			&i.CreatedAt,
			&i.BuyerEmail,
			&i.BuyerCompany,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliersByIDs = `-- name: ListSuppliersByIDs :many
SELECT id, name, name_zh, city, contact_email, verified_at
FROM suppliers
WHERE id = ANY($1::uuid[])
`

type ListSuppliersByIDsRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	NameZh       *string            `db:"name_zh" json:"name_zh"`
	City         string             `db:"city" json:"city"`
	ContactEmail *string            `db:"contact_email" json:"contact_email"`
	VerifiedAt   pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
}

func (q *Queries) ListSuppliersByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListSuppliersByIDsRow, error) {
	rows, err := q.db.Query(ctx, listSuppliersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuppliersByIDsRow{}
	for rows.Next() {
		var i ListSuppliersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameZh,
			&i.City,
			&i.ContactEmail,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRFQSeq = `-- name: NextRFQSeq :one
SELECT nextval('rfq_id_seq')::bigint
`

func (q *Queries) NextRFQSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextRFQSeq)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateRFQStatus = `-- name: UpdateRFQStatus :one
UPDATE rfqs SET status = $2 WHERE id = $1
RETURNING id, buyer_id, query_text, parsed_specs, matched_product_ids, status, qty, target_date, shipping_address, notes, created_at, buyer_email, buyer_company
`

type UpdateRFQStatusParams struct {
	ID     string `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) UpdateRFQStatus(ctx context.Context, arg UpdateRFQStatusParams) (Rfq, error) {
	row := q.db.QueryRow(ctx, updateRFQStatus, arg.ID, arg.Status)
	var i Rfq
	err := row.Scan(
		&i.ID,
		&i.BuyerID,
		&i.QueryText,
		&i.ParsedSpecs,
		&i.MatchedProductIds,
		&i.Status,
		&i.Qty,
		&i.TargetDate,
		&i.ShippingAddress,
		&i.Notes,
		&i.CreatedAt,
		&i.BuyerEmail,
		&i.BuyerCompany,
	)
	return i, err
}
