// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suppliers.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSuppliers = `-- name: CountSuppliers :one
SELECT COUNT(*)::int FROM suppliers
WHERE
    ($1::text IS NULL OR cluster = $1::text)
    AND ($2::boolean IS NOT TRUE OR verified_at IS NOT NULL)
`

type CountSuppliersParams struct {
	Cluster      *string `db:"cluster" json:"cluster"`
	VerifiedOnly *bool   `db:"verified_only" json:"verified_only"`
}

func (q *Queries) CountSuppliers(ctx context.Context, arg CountSuppliersParams) (int32, error) {
	row := q.db.QueryRow(ctx, countSuppliers, arg.Cluster, arg.VerifiedOnly)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (
    name, name_zh, city, country, cluster,
    capabilities, certifications,
    founded_year, employees, facility_size_m2, annual_output,
    on_time_rate, rating, order_count,
    verified_at, audit_report_url, photo_url,
    contact_email, contact_wechat
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17,
    $18, $19
)
RETURNING id, name, name_zh, city, country, cluster, capabilities, certifications, founded_year, employees, facility_size_m2, annual_output, on_time_rate, rating, order_count, verified_at, audit_report_url, photo_url, contact_email, contact_wechat, created_at
`

type CreateSupplierParams struct {
	Name           string             `db:"name" json:"name"`
	NameZh         *string            `db:"name_zh" json:"name_zh"`
	City           string             `db:"city" json:"city"`
	Country        string             `db:"country" json:"country"`
	Cluster        *string            `db:"cluster" json:"cluster"`
	Capabilities   []string           `db:"capabilities" json:"capabilities"`
	Certifications []string           `db:"certifications" json:"certifications"`
	FoundedYear    *int32             `db:"founded_year" json:"founded_year"`
	Employees      *int32             `db:"employees" json:"employees"`
	FacilitySizeM2 *int32             `db:"facility_size_m2" json:"facility_size_m2"`
	AnnualOutput   *string            `db:"annual_output" json:"annual_output"`
	OnTimeRate     pgtype.Numeric     `db:"on_time_rate" json:"on_time_rate"`
	Rating         pgtype.Numeric     `db:"rating" json:"rating"`
	OrderCount     int32              `db:"order_count" json:"order_count"`
	VerifiedAt     pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	AuditReportUrl *string            `db:"audit_report_url" json:"audit_report_url"`
	PhotoUrl       *string            `db:"photo_url" json:"photo_url"`
	ContactEmail   *string            `db:"contact_email" json:"contact_email"`
	ContactWechat  *string            `db:"contact_wechat" json:"contact_wechat"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.Name,
		arg.NameZh,
		arg.City,
		arg.Country,
		arg.Cluster,
		arg.Capabilities,
		arg.Certifications,
		arg.FoundedYear,
		arg.Employees,
		arg.FacilitySizeM2,
		arg.AnnualOutput,
		arg.OnTimeRate,
		arg.Rating,
		arg.OrderCount,
		arg.VerifiedAt,
		arg.AuditReportUrl,
		arg.PhotoUrl,
		arg.ContactEmail,
		arg.ContactWechat,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameZh,
		&i.City,
		&i.Country,
		&i.Cluster,
		&i.Capabilities,
		&i.Certifications,
		&i.FoundedYear,
		&i.Employees,
		&i.FacilitySizeM2,
		&i.AnnualOutput,
		&i.OnTimeRate,
		&i.Rating,
		&i.OrderCount,
		&i.VerifiedAt,
		&i.AuditReportUrl,
		&i.PhotoUrl,
		&i.ContactEmail,
		&i.ContactWechat,
		&i.CreatedAt,
	)
	return i, err
}

const getSupplierByID = `-- name: GetSupplierByID :one
SELECT id, name, name_zh, city, country, cluster, capabilities, certifications, founded_year, employees, facility_size_m2, annual_output, on_time_rate, rating, order_count, verified_at, audit_report_url, photo_url, contact_email, contact_wechat, created_at FROM suppliers WHERE id = $1
`

func (q *Queries) GetSupplierByID(ctx context.Context, id pgtype.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByID, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameZh,
		&i.City,
		&i.Country,
		&i.Cluster,
		&i.Capabilities,
		&i.Certifications,
		&i.FoundedYear,
		&i.Employees,
		&i.FacilitySizeM2,
		&i.AnnualOutput,
		&i.OnTimeRate,
		&i.Rating,
		&i.OrderCount,
		&i.VerifiedAt,
		&i.AuditReportUrl,
		&i.PhotoUrl,
		&i.ContactEmail,
		&i.ContactWechat,
		&i.CreatedAt,
	)
	return i, err
}

const getSupplierByName = `-- name: GetSupplierByName :one
SELECT id, name, name_zh, city, country, cluster, capabilities, certifications, founded_year, employees, facility_size_m2, annual_output, on_time_rate, rating, order_count, verified_at, audit_report_url, photo_url, contact_email, contact_wechat, created_at FROM suppliers WHERE name = $1 LIMIT 1
`

func (q *Queries) GetSupplierByName(ctx context.Context, name string) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByName, name)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameZh,
		&i.City,
		&i.Country,
		&i.Cluster,
		&i.Capabilities,
		&i.Certifications,
		&i.FoundedYear,
		&i.Employees,
		&i.FacilitySizeM2,
		&i.AnnualOutput,
		&i.OnTimeRate,
		&i.Rating,
		&i.OrderCount,
		&i.VerifiedAt,
		&i.AuditReportUrl,
		&i.PhotoUrl,
		&i.ContactEmail,
		&i.ContactWechat,
		&i.CreatedAt,
	)
	return i, err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, name, name_zh, city, country, cluster, capabilities, certifications, founded_year, employees, facility_size_m2, annual_output, on_time_rate, rating, order_count, verified_at, audit_report_url, photo_url, contact_email, contact_wechat, created_at FROM suppliers
WHERE
    ($3::text IS NULL OR cluster = $3::text)
    AND ($4::boolean IS NOT TRUE OR verified_at IS NOT NULL)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSuppliersParams struct {
	Limit        int32   `db:"limit" json:"limit"`
	Offset       int32   `db:"offset" json:"offset"`
	Cluster      *string `db:"cluster" json:"cluster"`
	VerifiedOnly *bool   `db:"verified_only" json:"verified_only"`
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers,
		arg.Limit,
		arg.Offset,
		arg.Cluster,
		arg.VerifiedOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameZh,
			&i.City,
			&i.Country,
			&i.Cluster,
			&i.Capabilities,
			&i.Certifications,
			&i.FoundedYear,
			&i.Employees,
			&i.FacilitySizeM2,
			&i.AnnualOutput,
			&i.OnTimeRate,
			&i.Rating,
			&i.OrderCount,
			&i.VerifiedAt,
			&i.AuditReportUrl,
			&i.PhotoUrl,
			&i.ContactEmail,
			&i.ContactWechat,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSupplier = `-- name: UpsertSupplier :one
INSERT INTO suppliers (
    id,
    name, name_zh, city, country, cluster,
    capabilities, certifications,
    founded_year, employees, facility_size_m2, annual_output,
    on_time_rate, rating,
    verified_at, audit_report_url, photo_url,
    contact_email, contact_wechat
) VALUES (
    $1,
    $2, $3, $4, $5, $6,
    $7, $8,
    $9, $10, $11, $12,
    $13, $14,
    $15, $16, $17,
    $18, $19
)
ON CONFLICT (id) DO UPDATE SET
    name              = EXCLUDED.name,
    name_zh           = EXCLUDED.name_zh,
    city              = EXCLUDED.city,
    country           = EXCLUDED.country,
    cluster           = EXCLUDED.cluster,
    capabilities      = EXCLUDED.capabilities,
    certifications    = EXCLUDED.certifications,
    founded_year      = EXCLUDED.founded_year,
    employees         = EXCLUDED.employees,
    facility_size_m2  = EXCLUDED.facility_size_m2,
    annual_output     = EXCLUDED.annual_output,
    on_time_rate      = EXCLUDED.on_time_rate,
    rating            = EXCLUDED.rating,
    verified_at       = EXCLUDED.verified_at,
    audit_report_url  = EXCLUDED.audit_report_url,
    photo_url         = EXCLUDED.photo_url,
    contact_email     = EXCLUDED.contact_email,
    contact_wechat    = EXCLUDED.contact_wechat
RETURNING id, name, name_zh, city, country, cluster, capabilities, certifications, founded_year, employees, facility_size_m2, annual_output, on_time_rate, rating, order_count, verified_at, audit_report_url, photo_url, contact_email, contact_wechat, created_at
`

type UpsertSupplierParams struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Name           string             `db:"name" json:"name"`
	NameZh         *string            `db:"name_zh" json:"name_zh"`
	City           string             `db:"city" json:"city"`
	Country        string             `db:"country" json:"country"`
	Cluster        *string            `db:"cluster" json:"cluster"`
	Capabilities   []string           `db:"capabilities" json:"capabilities"`
	Certifications []string           `db:"certifications" json:"certifications"`
	FoundedYear    *int32             `db:"founded_year" json:"founded_year"`
	Employees      *int32             `db:"employees" json:"employees"`
	FacilitySizeM2 *int32             `db:"facility_size_m2" json:"facility_size_m2"`
	AnnualOutput   *string            `db:"annual_output" json:"annual_output"`
	OnTimeRate     pgtype.Numeric     `db:"on_time_rate" json:"on_time_rate"`
	Rating         pgtype.Numeric     `db:"rating" json:"rating"`
	VerifiedAt     pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	AuditReportUrl *string            `db:"audit_report_url" json:"audit_report_url"`
	PhotoUrl       *string            `db:"photo_url" json:"photo_url"`
	ContactEmail   *string            `db:"contact_email" json:"contact_email"`
	ContactWechat  *string            `db:"contact_wechat" json:"contact_wechat"`
}

// Idempotent insert used by the seed CLI. Caller supplies a deterministic id
// (uuid5 of supplier slug); re-runs UPDATE the row in place rather than
// duplicating rows. order_count is preserved on UPDATE so seeding doesn't
// clobber live counters.
func (q *Queries) UpsertSupplier(ctx context.Context, arg UpsertSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, upsertSupplier,
		arg.ID,
		arg.Name,
		arg.NameZh,
		arg.City,
		arg.Country,
		arg.Cluster,
		arg.Capabilities,
		arg.Certifications,
		arg.FoundedYear,
		arg.Employees,
		arg.FacilitySizeM2,
		arg.AnnualOutput,
		arg.OnTimeRate,
		arg.Rating,
		arg.VerifiedAt,
		arg.AuditReportUrl,
		arg.PhotoUrl,
		arg.ContactEmail,
		arg.ContactWechat,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameZh,
		&i.City,
		&i.Country,
		&i.Cluster,
		&i.Capabilities,
		&i.Certifications,
		&i.FoundedYear,
		&i.Employees,
		&i.FacilitySizeM2,
		&i.AnnualOutput,
		&i.OnTimeRate,
		&i.Rating,
		&i.OrderCount,
		&i.VerifiedAt,
		&i.AuditReportUrl,
		&i.PhotoUrl,
		&i.ContactEmail,
		&i.ContactWechat,
		&i.CreatedAt,
	)
	return i, err
}
