// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: search/v1/search.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ParsedSpecs is the structured form of a buyer's natural-language query,
// produced by Claude tool-use spec extraction. Fields are the fiber-optic
// transceiver vertical's known dimensions; anything the query doesn't mention
// stays zero/empty. The results screen renders these as editable chips
// (GAU-247) and can send them back as SearchRequest.spec_overrides to re-rank
// without paying for another extraction.
type ParsedSpecs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataRate      string                 `protobuf:"bytes,1,opt,name=data_rate,json=dataRate,proto3" json:"data_rate,omitempty"`              // "100G", "10G", "1G"
	FormFactor    string                 `protobuf:"bytes,2,opt,name=form_factor,json=formFactor,proto3" json:"form_factor,omitempty"`        // "QSFP28", "QSFP", "SFP+", "SFP"
	ReachKm       float64                `protobuf:"fixed64,3,opt,name=reach_km,json=reachKm,proto3" json:"reach_km,omitempty"`               // 10, 0.3, 80
	WavelengthNm  int32                  `protobuf:"varint,4,opt,name=wavelength_nm,json=wavelengthNm,proto3" json:"wavelength_nm,omitempty"` // 1310, 850, 1550
	Compatibility []string               `protobuf:"bytes,5,rep,name=compatibility,proto3" json:"compatibility,omitempty"`                    // ["Cisco Nexus", "Arista"]
	FiberType     string                 `protobuf:"bytes,6,opt,name=fiber_type,json=fiberType,proto3" json:"fiber_type,omitempty"`           // "single-mode", "multi-mode"
	QtyEstimated  int32                  `protobuf:"varint,7,opt,name=qty_estimated,json=qtyEstimated,proto3" json:"qty_estimated,omitempty"`
	FreeText      string                 `protobuf:"bytes,8,opt,name=free_text,json=freeText,proto3" json:"free_text,omitempty"` // residual intent ("data center interconnect")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedSpecs) Reset() {
	*x = ParsedSpecs{}
	mi := &file_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedSpecs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedSpecs) ProtoMessage() {}

func (x *ParsedSpecs) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedSpecs.ProtoReflect.Descriptor instead.
func (*ParsedSpecs) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *ParsedSpecs) GetDataRate() string {
	if x != nil {
		return x.DataRate
	}
	return ""
}

func (x *ParsedSpecs) GetFormFactor() string {
	if x != nil {
		return x.FormFactor
	}
	return ""
}

func (x *ParsedSpecs) GetReachKm() float64 {
	if x != nil {
		return x.ReachKm
	}
	return 0
}

func (x *ParsedSpecs) GetWavelengthNm() int32 {
	if x != nil {
		return x.WavelengthNm
	}
	return 0
}

func (x *ParsedSpecs) GetCompatibility() []string {
	if x != nil {
		return x.Compatibility
	}
	return nil
}

func (x *ParsedSpecs) GetFiberType() string {
	if x != nil {
		return x.FiberType
	}
	return ""
}

func (x *ParsedSpecs) GetQtyEstimated() int32 {
	if x != nil {
		return x.QtyEstimated
	}
	return 0
}

func (x *ParsedSpecs) GetFreeText() string {
	if x != nil {
		return x.FreeText
	}
	return ""
}

type SearchRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Query            string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	RequestingUserId string                 `protobuf:"bytes,2,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"`
	Limit            int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // max results; service clamps (default 20)
	// When set, the service skips Claude spec extraction and ranks against these
	// directly. Used by the editable-chip UI to re-run search after an edit.
	SpecOverrides *ParsedSpecs `protobuf:"bytes,4,opt,name=spec_overrides,json=specOverrides,proto3" json:"spec_overrides,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetRequestingUserId() string {
	if x != nil {
		return x.RequestingUserId
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetSpecOverrides() *ParsedSpecs {
	if x != nil {
		return x.SpecOverrides
	}
	return nil
}

// ProductHit mirrors a products row plus the denormalized supplier display
// fields the results screen needs (so it renders without a second round-trip)
// and the ranking signals from the hybrid pipeline.
type ProductHit struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SupplierId       string                 `protobuf:"bytes,2,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	Sku              string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NameZh           string                 `protobuf:"bytes,5,opt,name=name_zh,json=nameZh,proto3" json:"name_zh,omitempty"`
	Category         string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Specs            *structpb.Struct       `protobuf:"bytes,7,opt,name=specs,proto3" json:"specs,omitempty"`
	PriceUsd         float64                `protobuf:"fixed64,8,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	Moq              int32                  `protobuf:"varint,9,opt,name=moq,proto3" json:"moq,omitempty"`
	StockQty         int32                  `protobuf:"varint,10,opt,name=stock_qty,json=stockQty,proto3" json:"stock_qty,omitempty"`
	LeadTimeDays     int32                  `protobuf:"varint,11,opt,name=lead_time_days,json=leadTimeDays,proto3" json:"lead_time_days,omitempty"`
	DatasheetUrl     string                 `protobuf:"bytes,12,opt,name=datasheet_url,json=datasheetUrl,proto3" json:"datasheet_url,omitempty"`
	SupplierName     string                 `protobuf:"bytes,13,opt,name=supplier_name,json=supplierName,proto3" json:"supplier_name,omitempty"`
	SupplierCity     string                 `protobuf:"bytes,14,opt,name=supplier_city,json=supplierCity,proto3" json:"supplier_city,omitempty"`
	SupplierVerified bool                   `protobuf:"varint,15,opt,name=supplier_verified,json=supplierVerified,proto3" json:"supplier_verified,omitempty"`
	MatchScore       float64                `protobuf:"fixed64,16,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`                 // 0..100, vector closeness blended with spec fit
	VectorDistance   float64                `protobuf:"fixed64,17,opt,name=vector_distance,json=vectorDistance,proto3" json:"vector_distance,omitempty"`     // raw pgvector cosine distance (lower = closer)
	MatchExplanation string                 `protobuf:"bytes,18,opt,name=match_explanation,json=matchExplanation,proto3" json:"match_explanation,omitempty"` // one-line "why this matches", from Claude
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProductHit) Reset() {
	*x = ProductHit{}
	mi := &file_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductHit) ProtoMessage() {}

func (x *ProductHit) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductHit.ProtoReflect.Descriptor instead.
func (*ProductHit) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *ProductHit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductHit) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *ProductHit) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductHit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductHit) GetNameZh() string {
	if x != nil {
		return x.NameZh
	}
	return ""
}

func (x *ProductHit) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductHit) GetSpecs() *structpb.Struct {
	if x != nil {
		return x.Specs
	}
	return nil
}

func (x *ProductHit) GetPriceUsd() float64 {
	if x != nil {
		return x.PriceUsd
	}
	return 0
}

func (x *ProductHit) GetMoq() int32 {
	if x != nil {
		return x.Moq
	}
	return 0
}

func (x *ProductHit) GetStockQty() int32 {
	if x != nil {
		return x.StockQty
	}
	return 0
}

func (x *ProductHit) GetLeadTimeDays() int32 {
	if x != nil {
		return x.LeadTimeDays
	}
	return 0
}

func (x *ProductHit) GetDatasheetUrl() string {
	if x != nil {
		return x.DatasheetUrl
	}
	return ""
}

func (x *ProductHit) GetSupplierName() string {
	if x != nil {
		return x.SupplierName
	}
	return ""
}

func (x *ProductHit) GetSupplierCity() string {
	if x != nil {
		return x.SupplierCity
	}
	return ""
}

func (x *ProductHit) GetSupplierVerified() bool {
	if x != nil {
		return x.SupplierVerified
	}
	return false
}

func (x *ProductHit) GetMatchScore() float64 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

func (x *ProductHit) GetVectorDistance() float64 {
	if x != nil {
		return x.VectorDistance
	}
	return 0
}

func (x *ProductHit) GetMatchExplanation() string {
	if x != nil {
		return x.MatchExplanation
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParsedSpecs   *ParsedSpecs           `protobuf:"bytes,1,opt,name=parsed_specs,json=parsedSpecs,proto3" json:"parsed_specs,omitempty"`
	Results       []*ProductHit          `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	QueryId       string                 `protobuf:"bytes,3,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"` // telemetry / cache correlation id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetParsedSpecs() *ParsedSpecs {
	if x != nil {
		return x.ParsedSpecs
	}
	return nil
}

func (x *SearchResponse) GetResults() []*ProductHit {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

var File_search_v1_search_proto protoreflect.FileDescriptor

const file_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x16search/v1/search.proto\x12\tsearch.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x92\x02\n" +
	"\vParsedSpecs\x12\x1b\n" +
	"\tdata_rate\x18\x01 \x01(\tR\bdataRate\x12\x1f\n" +
	"\vform_factor\x18\x02 \x01(\tR\n" +
	"formFactor\x12\x19\n" +
	"\breach_km\x18\x03 \x01(\x01R\areachKm\x12#\n" +
	"\rwavelength_nm\x18\x04 \x01(\x05R\fwavelengthNm\x12$\n" +
	"\rcompatibility\x18\x05 \x03(\tR\rcompatibility\x12\x1d\n" +
	"\n" +
	"fiber_type\x18\x06 \x01(\tR\tfiberType\x12#\n" +
	"\rqty_estimated\x18\a \x01(\x05R\fqtyEstimated\x12\x1b\n" +
	"\tfree_text\x18\b \x01(\tR\bfreeText\"\xa8\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12,\n" +
	"\x12requesting_user_id\x18\x02 \x01(\tR\x10requestingUserId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12=\n" +
	"\x0espec_overrides\x18\x04 \x01(\v2\x16.search.v1.ParsedSpecsR\rspecOverrides\"\xcc\x04\n" +
	"\n" +
	"ProductHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsupplier_id\x18\x02 \x01(\tR\n" +
	"supplierId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x17\n" +
	"\aname_zh\x18\x05 \x01(\tR\x06nameZh\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12-\n" +
	"\x05specs\x18\a \x01(\v2\x17.google.protobuf.StructR\x05specs\x12\x1b\n" +
	"\tprice_usd\x18\b \x01(\x01R\bpriceUsd\x12\x10\n" +
	"\x03moq\x18\t \x01(\x05R\x03moq\x12\x1b\n" +
	"\tstock_qty\x18\n" +
	" \x01(\x05R\bstockQty\x12$\n" +
	"\x0elead_time_days\x18\v \x01(\x05R\fleadTimeDays\x12#\n" +
	"\rdatasheet_url\x18\f \x01(\tR\fdatasheetUrl\x12#\n" +
	"\rsupplier_name\x18\r \x01(\tR\fsupplierName\x12#\n" +
	"\rsupplier_city\x18\x0e \x01(\tR\fsupplierCity\x12+\n" +
	"\x11supplier_verified\x18\x0f \x01(\bR\x10supplierVerified\x12\x1f\n" +
	"\vmatch_score\x18\x10 \x01(\x01R\n" +
	"matchScore\x12'\n" +
	"\x0fvector_distance\x18\x11 \x01(\x01R\x0evectorDistance\x12+\n" +
	"\x11match_explanation\x18\x12 \x01(\tR\x10matchExplanation\"\x97\x01\n" +
	"\x0eSearchResponse\x129\n" +
	"\fparsed_specs\x18\x01 \x01(\v2\x16.search.v1.ParsedSpecsR\vparsedSpecs\x12/\n" +
	"\aresults\x18\x02 \x03(\v2\x15.search.v1.ProductHitR\aresults\x12\x19\n" +
	"\bquery_id\x18\x03 \x01(\tR\aqueryId2\x8d\x01\n" +
	"\rSearchService\x12=\n" +
	"\x06Search\x12\x18.search.v1.SearchRequest\x1a\x19.search.v1.SearchResponse\x12=\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBAZ?github.com/nikitashilov/microblog_grpc/proto/search/v1;searchv1b\x06proto3"

var (
	file_search_v1_search_proto_rawDescOnce sync.Once
	file_search_v1_search_proto_rawDescData []byte
)

func file_search_v1_search_proto_rawDescGZIP() []byte {
	file_search_v1_search_proto_rawDescOnce.Do(func() {
		file_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)))
	})
	return file_search_v1_search_proto_rawDescData
}

var file_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_search_v1_search_proto_goTypes = []any{
	(*ParsedSpecs)(nil),     // 0: search.v1.ParsedSpecs
	(*SearchRequest)(nil),   // 1: search.v1.SearchRequest
	(*ProductHit)(nil),      // 2: search.v1.ProductHit
	(*SearchResponse)(nil),  // 3: search.v1.SearchResponse
	(*structpb.Struct)(nil), // 4: google.protobuf.Struct
	(*emptypb.Empty)(nil),   // 5: google.protobuf.Empty
}
var file_search_v1_search_proto_depIdxs = []int32{
	0, // 0: search.v1.SearchRequest.spec_overrides:type_name -> search.v1.ParsedSpecs
	4, // 1: search.v1.ProductHit.specs:type_name -> google.protobuf.Struct
	0, // 2: search.v1.SearchResponse.parsed_specs:type_name -> search.v1.ParsedSpecs
	2, // 3: search.v1.SearchResponse.results:type_name -> search.v1.ProductHit
	1, // 4: search.v1.SearchService.Search:input_type -> search.v1.SearchRequest
	5, // 5: search.v1.SearchService.HealthCheck:input_type -> google.protobuf.Empty
	3, // 6: search.v1.SearchService.Search:output_type -> search.v1.SearchResponse
	5, // 7: search.v1.SearchService.HealthCheck:output_type -> google.protobuf.Empty
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_search_v1_search_proto_init() }
func file_search_v1_search_proto_init() {
	if File_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_v1_search_proto_goTypes,
		DependencyIndexes: file_search_v1_search_proto_depIdxs,
		MessageInfos:      file_search_v1_search_proto_msgTypes,
	}.Build()
	File_search_v1_search_proto = out.File
	file_search_v1_search_proto_goTypes = nil
	file_search_v1_search_proto_depIdxs = nil
}
