// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: order/v1/order.proto

package orderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderStatus values mirror the CHECK constraint on orders.status.
// Kept as a plain string field in the proto (rather than an enum) to keep the
// state machine entirely in Go — the proto file is otherwise touched any time
// a new state is added. See Order Service Architecture doc for the full FSM.
type Order struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                          // ORD-YYYYMMDD-NNNN-SFO
	BuyerId            string                 `protobuf:"bytes,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"` // soft ref to users(id) in user-service
	SupplierId         string                 `protobuf:"bytes,3,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	QuoteId            string                 `protobuf:"bytes,4,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	RfqId              string                 `protobuf:"bytes,5,opt,name=rfq_id,json=rfqId,proto3" json:"rfq_id,omitempty"`
	Status             string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	PaymentStatus      string                 `protobuf:"bytes,7,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"` // unpaid | paid | refunded
	QcStatus           string                 `protobuf:"bytes,8,opt,name=qc_status,json=qcStatus,proto3" json:"qc_status,omitempty"`                // null | pending | in_progress | passed | failed
	TotalUsd           float64                `protobuf:"fixed64,9,opt,name=total_usd,json=totalUsd,proto3" json:"total_usd,omitempty"`
	ShippingAddress    string                 `protobuf:"bytes,10,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	ShippingCity       string                 `protobuf:"bytes,11,opt,name=shipping_city,json=shippingCity,proto3" json:"shipping_city,omitempty"`
	ShippingCountry    string                 `protobuf:"bytes,12,opt,name=shipping_country,json=shippingCountry,proto3" json:"shipping_country,omitempty"`
	WarrantyUntil      string                 `protobuf:"bytes,13,opt,name=warranty_until,json=warrantyUntil,proto3" json:"warranty_until,omitempty"` // ISO-8601 date
	CancelledAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	CancellationReason string                 `protobuf:"bytes,15,opt,name=cancellation_reason,json=cancellationReason,proto3" json:"cancellation_reason,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *Order) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *Order) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *Order) GetRfqId() string {
	if x != nil {
		return x.RfqId
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *Order) GetQcStatus() string {
	if x != nil {
		return x.QcStatus
	}
	return ""
}

func (x *Order) GetTotalUsd() float64 {
	if x != nil {
		return x.TotalUsd
	}
	return 0
}

func (x *Order) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

func (x *Order) GetShippingCity() string {
	if x != nil {
		return x.ShippingCity
	}
	return ""
}

func (x *Order) GetShippingCountry() string {
	if x != nil {
		return x.ShippingCountry
	}
	return ""
}

func (x *Order) GetWarrantyUntil() string {
	if x != nil {
		return x.WarrantyUntil
	}
	return ""
}

func (x *Order) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

func (x *Order) GetCancellationReason() string {
	if x != nil {
		return x.CancellationReason
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type OrderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	FromStatus    string                 `protobuf:"bytes,4,opt,name=from_status,json=fromStatus,proto3" json:"from_status,omitempty"`
	ToStatus      string                 `protobuf:"bytes,5,opt,name=to_status,json=toStatus,proto3" json:"to_status,omitempty"`
	ActorId       string                 `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorType     string                 `protobuf:"bytes,7,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"` // buyer | supplier | admin | system | inspector | carrier
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	OccurredTz    string                 `protobuf:"bytes,9,opt,name=occurred_tz,json=occurredTz,proto3" json:"occurred_tz,omitempty"`
	Location      string                 `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,11,opt,name=payload,proto3" json:"payload,omitempty"`
	Documents     *structpb.Struct       `protobuf:"bytes,12,opt,name=documents,proto3" json:"documents,omitempty"`
	Notes         string                 `protobuf:"bytes,13,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEvent) Reset() {
	*x = OrderEvent{}
	mi := &file_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEvent) ProtoMessage() {}

func (x *OrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEvent.ProtoReflect.Descriptor instead.
func (*OrderEvent) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OrderEvent) GetFromStatus() string {
	if x != nil {
		return x.FromStatus
	}
	return ""
}

func (x *OrderEvent) GetToStatus() string {
	if x != nil {
		return x.ToStatus
	}
	return ""
}

func (x *OrderEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *OrderEvent) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *OrderEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *OrderEvent) GetOccurredTz() string {
	if x != nil {
		return x.OccurredTz
	}
	return ""
}

func (x *OrderEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *OrderEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OrderEvent) GetDocuments() *structpb.Struct {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *OrderEvent) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *OrderEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestingUserId string                 `protobuf:"bytes,2,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrderRequest) GetRequestingUserId() string {
	if x != nil {
		return x.RequestingUserId
	}
	return ""
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerId       string                 `protobuf:"bytes,1,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	SupplierId    string                 `protobuf:"bytes,2,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrdersRequest) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *ListOrdersRequest) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *ListOrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// AppendEvent is the only mutator for state transitions. Idempotent on
// (order_id, event_type, occurred_at) — see the UNIQUE constraint on
// order_events. Callers must supply a deterministic occurred_at for retries.
type AppendEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *OrderEvent            `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEventRequest) Reset() {
	*x = AppendEventRequest{}
	mi := &file_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventRequest) ProtoMessage() {}

func (x *AppendEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventRequest.ProtoReflect.Descriptor instead.
func (*AppendEventRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *AppendEventRequest) GetEvent() *OrderEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *ListEventsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*OrderEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_order_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *ListEventsResponse) GetEvents() []*OrderEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_order_v1_order_proto protoreflect.FileDescriptor

const file_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x14order/v1/order.proto\x12\border.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x05\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\tR\abuyerId\x12\x1f\n" +
	"\vsupplier_id\x18\x03 \x01(\tR\n" +
	"supplierId\x12\x19\n" +
	"\bquote_id\x18\x04 \x01(\tR\aquoteId\x12\x15\n" +
	"\x06rfq_id\x18\x05 \x01(\tR\x05rfqId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0epayment_status\x18\a \x01(\tR\rpaymentStatus\x12\x1b\n" +
	"\tqc_status\x18\b \x01(\tR\bqcStatus\x12\x1b\n" +
	"\ttotal_usd\x18\t \x01(\x01R\btotalUsd\x12)\n" +
	"\x10shipping_address\x18\n" +
	" \x01(\tR\x0fshippingAddress\x12#\n" +
	"\rshipping_city\x18\v \x01(\tR\fshippingCity\x12)\n" +
	"\x10shipping_country\x18\f \x01(\tR\x0fshippingCountry\x12%\n" +
	"\x0ewarranty_until\x18\r \x01(\tR\rwarrantyUntil\x12=\n" +
	"\fcancelled_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\x12/\n" +
	"\x13cancellation_reason\x18\x0f \x01(\tR\x12cancellationReason\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x83\x04\n" +
	"\n" +
	"OrderEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1f\n" +
	"\vfrom_status\x18\x04 \x01(\tR\n" +
	"fromStatus\x12\x1b\n" +
	"\tto_status\x18\x05 \x01(\tR\btoStatus\x12\x19\n" +
	"\bactor_id\x18\x06 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\a \x01(\tR\tactorType\x12;\n" +
	"\voccurred_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1f\n" +
	"\voccurred_tz\x18\t \x01(\tR\n" +
	"occurredTz\x12\x1a\n" +
	"\blocation\x18\n" +
	" \x01(\tR\blocation\x121\n" +
	"\apayload\x18\v \x01(\v2\x17.google.protobuf.StructR\apayload\x125\n" +
	"\tdocuments\x18\f \x01(\v2\x17.google.protobuf.StructR\tdocuments\x12\x14\n" +
	"\x05notes\x18\r \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\";\n" +
	"\x12CreateOrderRequest\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\"O\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12requesting_user_id\x18\x02 \x01(\tR\x10requestingUserId\"\x95\x01\n" +
	"\x11ListOrdersRequest\x12\x19\n" +
	"\bbuyer_id\x18\x01 \x01(\tR\abuyerId\x12\x1f\n" +
	"\vsupplier_id\x18\x02 \x01(\tR\n" +
	"supplierId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"S\n" +
	"\x12ListOrdersResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order.v1.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"@\n" +
	"\x12AppendEventRequest\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.order.v1.OrderEventR\x05event\".\n" +
	"\x11ListEventsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"B\n" +
	"\x12ListEventsResponse\x12,\n" +
	"\x06events\x18\x01 \x03(\v2\x14.order.v1.OrderEventR\x06events2\x98\x03\n" +
	"\fOrderService\x12<\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x0f.order.v1.Order\x126\n" +
	"\bGetOrder\x12\x19.order.v1.GetOrderRequest\x1a\x0f.order.v1.Order\x12G\n" +
	"\n" +
	"ListOrders\x12\x1b.order.v1.ListOrdersRequest\x1a\x1c.order.v1.ListOrdersResponse\x12A\n" +
	"\vAppendEvent\x12\x1c.order.v1.AppendEventRequest\x1a\x14.order.v1.OrderEvent\x12G\n" +
	"\n" +
	"ListEvents\x12\x1b.order.v1.ListEventsRequest\x1a\x1c.order.v1.ListEventsResponse\x12=\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB?Z=github.com/nikitashilov/microblog_grpc/proto/order/v1;orderv1b\x06proto3"

var (
	file_order_v1_order_proto_rawDescOnce sync.Once
	file_order_v1_order_proto_rawDescData []byte
)

func file_order_v1_order_proto_rawDescGZIP() []byte {
	file_order_v1_order_proto_rawDescOnce.Do(func() {
		file_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)))
	})
	return file_order_v1_order_proto_rawDescData
}

var file_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_order_v1_order_proto_goTypes = []any{
	(*Order)(nil),                 // 0: order.v1.Order
	(*OrderEvent)(nil),            // 1: order.v1.OrderEvent
	(*CreateOrderRequest)(nil),    // 2: order.v1.CreateOrderRequest
	(*GetOrderRequest)(nil),       // 3: order.v1.GetOrderRequest
	(*ListOrdersRequest)(nil),     // 4: order.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),    // 5: order.v1.ListOrdersResponse
	(*AppendEventRequest)(nil),    // 6: order.v1.AppendEventRequest
	(*ListEventsRequest)(nil),     // 7: order.v1.ListEventsRequest
	(*ListEventsResponse)(nil),    // 8: order.v1.ListEventsResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 10: google.protobuf.Struct
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_order_v1_order_proto_depIdxs = []int32{
	9,  // 0: order.v1.Order.cancelled_at:type_name -> google.protobuf.Timestamp
	9,  // 1: order.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: order.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 3: order.v1.OrderEvent.occurred_at:type_name -> google.protobuf.Timestamp
	10, // 4: order.v1.OrderEvent.payload:type_name -> google.protobuf.Struct
	10, // 5: order.v1.OrderEvent.documents:type_name -> google.protobuf.Struct
	9,  // 6: order.v1.OrderEvent.created_at:type_name -> google.protobuf.Timestamp
	0,  // 7: order.v1.CreateOrderRequest.order:type_name -> order.v1.Order
	0,  // 8: order.v1.ListOrdersResponse.orders:type_name -> order.v1.Order
	1,  // 9: order.v1.AppendEventRequest.event:type_name -> order.v1.OrderEvent
	1,  // 10: order.v1.ListEventsResponse.events:type_name -> order.v1.OrderEvent
	2,  // 11: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	3,  // 12: order.v1.OrderService.GetOrder:input_type -> order.v1.GetOrderRequest
	4,  // 13: order.v1.OrderService.ListOrders:input_type -> order.v1.ListOrdersRequest
	6,  // 14: order.v1.OrderService.AppendEvent:input_type -> order.v1.AppendEventRequest
	7,  // 15: order.v1.OrderService.ListEvents:input_type -> order.v1.ListEventsRequest
	11, // 16: order.v1.OrderService.HealthCheck:input_type -> google.protobuf.Empty
	0,  // 17: order.v1.OrderService.CreateOrder:output_type -> order.v1.Order
	0,  // 18: order.v1.OrderService.GetOrder:output_type -> order.v1.Order
	5,  // 19: order.v1.OrderService.ListOrders:output_type -> order.v1.ListOrdersResponse
	1,  // 20: order.v1.OrderService.AppendEvent:output_type -> order.v1.OrderEvent
	8,  // 21: order.v1.OrderService.ListEvents:output_type -> order.v1.ListEventsResponse
	11, // 22: order.v1.OrderService.HealthCheck:output_type -> google.protobuf.Empty
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_order_v1_order_proto_init() }
func file_order_v1_order_proto_init() {
	if File_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_order_proto_goTypes,
		DependencyIndexes: file_order_v1_order_proto_depIdxs,
		MessageInfos:      file_order_v1_order_proto_msgTypes,
	}.Build()
	File_order_v1_order_proto = out.File
	file_order_v1_order_proto_goTypes = nil
	file_order_v1_order_proto_depIdxs = nil
}
