// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: supplier/v1/supplier.proto

package supplierv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Supplier struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // uuid
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameZh         string                 `protobuf:"bytes,3,opt,name=name_zh,json=nameZh,proto3" json:"name_zh,omitempty"`
	City           string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Country        string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"` // default "CN"
	Cluster        string                 `protobuf:"bytes,6,opt,name=cluster,proto3" json:"cluster,omitempty"` // e.g. "Shenzhen", "Dongguan"
	Capabilities   []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Certifications []string               `protobuf:"bytes,8,rep,name=certifications,proto3" json:"certifications,omitempty"`
	FoundedYear    int32                  `protobuf:"varint,9,opt,name=founded_year,json=foundedYear,proto3" json:"founded_year,omitempty"`
	Employees      int32                  `protobuf:"varint,10,opt,name=employees,proto3" json:"employees,omitempty"`
	FacilitySizeM2 int32                  `protobuf:"varint,11,opt,name=facility_size_m2,json=facilitySizeM2,proto3" json:"facility_size_m2,omitempty"`
	AnnualOutput   string                 `protobuf:"bytes,12,opt,name=annual_output,json=annualOutput,proto3" json:"annual_output,omitempty"`
	OnTimeRate     float64                `protobuf:"fixed64,13,opt,name=on_time_rate,json=onTimeRate,proto3" json:"on_time_rate,omitempty"` // 0..100
	Rating         float64                `protobuf:"fixed64,14,opt,name=rating,proto3" json:"rating,omitempty"`                             // 0..5
	OrderCount     int32                  `protobuf:"varint,15,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	VerifiedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	AuditReportUrl string                 `protobuf:"bytes,17,opt,name=audit_report_url,json=auditReportUrl,proto3" json:"audit_report_url,omitempty"`
	PhotoUrl       string                 `protobuf:"bytes,18,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	ContactEmail   string                 `protobuf:"bytes,19,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	ContactWechat  string                 `protobuf:"bytes,20,opt,name=contact_wechat,json=contactWechat,proto3" json:"contact_wechat,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Supplier) Reset() {
	*x = Supplier{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Supplier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Supplier) ProtoMessage() {}

func (x *Supplier) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Supplier.ProtoReflect.Descriptor instead.
func (*Supplier) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{0}
}

func (x *Supplier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Supplier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Supplier) GetNameZh() string {
	if x != nil {
		return x.NameZh
	}
	return ""
}

func (x *Supplier) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Supplier) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Supplier) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Supplier) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Supplier) GetCertifications() []string {
	if x != nil {
		return x.Certifications
	}
	return nil
}

func (x *Supplier) GetFoundedYear() int32 {
	if x != nil {
		return x.FoundedYear
	}
	return 0
}

func (x *Supplier) GetEmployees() int32 {
	if x != nil {
		return x.Employees
	}
	return 0
}

func (x *Supplier) GetFacilitySizeM2() int32 {
	if x != nil {
		return x.FacilitySizeM2
	}
	return 0
}

func (x *Supplier) GetAnnualOutput() string {
	if x != nil {
		return x.AnnualOutput
	}
	return ""
}

func (x *Supplier) GetOnTimeRate() float64 {
	if x != nil {
		return x.OnTimeRate
	}
	return 0
}

func (x *Supplier) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Supplier) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *Supplier) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *Supplier) GetAuditReportUrl() string {
	if x != nil {
		return x.AuditReportUrl
	}
	return ""
}

func (x *Supplier) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *Supplier) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *Supplier) GetContactWechat() string {
	if x != nil {
		return x.ContactWechat
	}
	return ""
}

func (x *Supplier) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateSupplierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supplier      *Supplier              `protobuf:"bytes,1,opt,name=supplier,proto3" json:"supplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSupplierRequest) Reset() {
	*x = CreateSupplierRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSupplierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSupplierRequest) ProtoMessage() {}

func (x *CreateSupplierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSupplierRequest.ProtoReflect.Descriptor instead.
func (*CreateSupplierRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSupplierRequest) GetSupplier() *Supplier {
	if x != nil {
		return x.Supplier
	}
	return nil
}

type GetSupplierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupplierRequest) Reset() {
	*x = GetSupplierRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupplierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplierRequest) ProtoMessage() {}

func (x *GetSupplierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplierRequest.ProtoReflect.Descriptor instead.
func (*GetSupplierRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{2}
}

func (x *GetSupplierRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSuppliersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Cluster       string                 `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"` // optional filter
	VerifiedOnly  bool                   `protobuf:"varint,4,opt,name=verified_only,json=verifiedOnly,proto3" json:"verified_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSuppliersRequest) Reset() {
	*x = ListSuppliersRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSuppliersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSuppliersRequest) ProtoMessage() {}

func (x *ListSuppliersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSuppliersRequest.ProtoReflect.Descriptor instead.
func (*ListSuppliersRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{3}
}

func (x *ListSuppliersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSuppliersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListSuppliersRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ListSuppliersRequest) GetVerifiedOnly() bool {
	if x != nil {
		return x.VerifiedOnly
	}
	return false
}

type ListSuppliersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suppliers     []*Supplier            `protobuf:"bytes,1,rep,name=suppliers,proto3" json:"suppliers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSuppliersResponse) Reset() {
	*x = ListSuppliersResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSuppliersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSuppliersResponse) ProtoMessage() {}

func (x *ListSuppliersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSuppliersResponse.ProtoReflect.Descriptor instead.
func (*ListSuppliersResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{4}
}

func (x *ListSuppliersResponse) GetSuppliers() []*Supplier {
	if x != nil {
		return x.Suppliers
	}
	return nil
}

func (x *ListSuppliersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_supplier_v1_supplier_proto protoreflect.FileDescriptor

const file_supplier_v1_supplier_proto_rawDesc = "" +
	"\n" +
	"\x1asupplier/v1/supplier.proto\x12\vsupplier.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x05\n" +
	"\bSupplier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aname_zh\x18\x03 \x01(\tR\x06nameZh\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x18\n" +
	"\acluster\x18\x06 \x01(\tR\acluster\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x12&\n" +
	"\x0ecertifications\x18\b \x03(\tR\x0ecertifications\x12!\n" +
	"\ffounded_year\x18\t \x01(\x05R\vfoundedYear\x12\x1c\n" +
	"\temployees\x18\n" +
	" \x01(\x05R\temployees\x12(\n" +
	"\x10facility_size_m2\x18\v \x01(\x05R\x0efacilitySizeM2\x12#\n" +
	"\rannual_output\x18\f \x01(\tR\fannualOutput\x12 \n" +
	"\fon_time_rate\x18\r \x01(\x01R\n" +
	"onTimeRate\x12\x16\n" +
	"\x06rating\x18\x0e \x01(\x01R\x06rating\x12\x1f\n" +
	"\vorder_count\x18\x0f \x01(\x05R\n" +
	"orderCount\x12;\n" +
	"\vverified_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x12(\n" +
	"\x10audit_report_url\x18\x11 \x01(\tR\x0eauditReportUrl\x12\x1b\n" +
	"\tphoto_url\x18\x12 \x01(\tR\bphotoUrl\x12#\n" +
	"\rcontact_email\x18\x13 \x01(\tR\fcontactEmail\x12%\n" +
	"\x0econtact_wechat\x18\x14 \x01(\tR\rcontactWechat\x129\n" +
	"\n" +
	"created_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"J\n" +
	"\x15CreateSupplierRequest\x121\n" +
	"\bsupplier\x18\x01 \x01(\v2\x15.supplier.v1.SupplierR\bsupplier\"$\n" +
	"\x12GetSupplierRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x83\x01\n" +
	"\x14ListSuppliersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x18\n" +
	"\acluster\x18\x03 \x01(\tR\acluster\x12#\n" +
	"\rverified_only\x18\x04 \x01(\bR\fverifiedOnly\"b\n" +
	"\x15ListSuppliersResponse\x123\n" +
	"\tsuppliers\x18\x01 \x03(\v2\x15.supplier.v1.SupplierR\tsuppliers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xbc\x02\n" +
	"\x0fSupplierService\x12K\n" +
	"\x0eCreateSupplier\x12\".supplier.v1.CreateSupplierRequest\x1a\x15.supplier.v1.Supplier\x12E\n" +
	"\vGetSupplier\x12\x1f.supplier.v1.GetSupplierRequest\x1a\x15.supplier.v1.Supplier\x12V\n" +
	"\rListSuppliers\x12!.supplier.v1.ListSuppliersRequest\x1a\".supplier.v1.ListSuppliersResponse\x12=\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBEZCgithub.com/nikitashilov/microblog_grpc/proto/supplier/v1;supplierv1b\x06proto3"

var (
	file_supplier_v1_supplier_proto_rawDescOnce sync.Once
	file_supplier_v1_supplier_proto_rawDescData []byte
)

func file_supplier_v1_supplier_proto_rawDescGZIP() []byte {
	file_supplier_v1_supplier_proto_rawDescOnce.Do(func() {
		file_supplier_v1_supplier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_supplier_v1_supplier_proto_rawDesc), len(file_supplier_v1_supplier_proto_rawDesc)))
	})
	return file_supplier_v1_supplier_proto_rawDescData
}

var file_supplier_v1_supplier_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_supplier_v1_supplier_proto_goTypes = []any{
	(*Supplier)(nil),              // 0: supplier.v1.Supplier
	(*CreateSupplierRequest)(nil), // 1: supplier.v1.CreateSupplierRequest
	(*GetSupplierRequest)(nil),    // 2: supplier.v1.GetSupplierRequest
	(*ListSuppliersRequest)(nil),  // 3: supplier.v1.ListSuppliersRequest
	(*ListSuppliersResponse)(nil), // 4: supplier.v1.ListSuppliersResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_supplier_v1_supplier_proto_depIdxs = []int32{
	5, // 0: supplier.v1.Supplier.verified_at:type_name -> google.protobuf.Timestamp
	5, // 1: supplier.v1.Supplier.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: supplier.v1.CreateSupplierRequest.supplier:type_name -> supplier.v1.Supplier
	0, // 3: supplier.v1.ListSuppliersResponse.suppliers:type_name -> supplier.v1.Supplier
	1, // 4: supplier.v1.SupplierService.CreateSupplier:input_type -> supplier.v1.CreateSupplierRequest
	2, // 5: supplier.v1.SupplierService.GetSupplier:input_type -> supplier.v1.GetSupplierRequest
	3, // 6: supplier.v1.SupplierService.ListSuppliers:input_type -> supplier.v1.ListSuppliersRequest
	6, // 7: supplier.v1.SupplierService.HealthCheck:input_type -> google.protobuf.Empty
	0, // 8: supplier.v1.SupplierService.CreateSupplier:output_type -> supplier.v1.Supplier
	0, // 9: supplier.v1.SupplierService.GetSupplier:output_type -> supplier.v1.Supplier
	4, // 10: supplier.v1.SupplierService.ListSuppliers:output_type -> supplier.v1.ListSuppliersResponse
	6, // 11: supplier.v1.SupplierService.HealthCheck:output_type -> google.protobuf.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_supplier_v1_supplier_proto_init() }
func file_supplier_v1_supplier_proto_init() {
	if File_supplier_v1_supplier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_supplier_v1_supplier_proto_rawDesc), len(file_supplier_v1_supplier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_supplier_v1_supplier_proto_goTypes,
		DependencyIndexes: file_supplier_v1_supplier_proto_depIdxs,
		MessageInfos:      file_supplier_v1_supplier_proto_msgTypes,
	}.Build()
	File_supplier_v1_supplier_proto = out.File
	file_supplier_v1_supplier_proto_goTypes = nil
	file_supplier_v1_supplier_proto_depIdxs = nil
}
