// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: product/v1/product.proto

package productv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Product mirrors the `products` row. Specs is intentionally Struct (free-form
// JSON) so different categories — transceivers, fibers, lasers — can carry
// their own structured attributes without proto churn. The hybrid AI search
// still keys off top-level fields it knows: data_rate, form_factor, reach_km, etc.
type Product struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // uuid
	SupplierId   string                 `protobuf:"bytes,2,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"` // uuid (suppliers.id)
	Sku          string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Name         string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NameZh       string                 `protobuf:"bytes,5,opt,name=name_zh,json=nameZh,proto3" json:"name_zh,omitempty"`
	Category     string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"` // transceiver | fiber | laser | ...
	Specs        *structpb.Struct       `protobuf:"bytes,7,opt,name=specs,proto3" json:"specs,omitempty"`
	PriceUsd     float64                `protobuf:"fixed64,8,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	Moq          int32                  `protobuf:"varint,9,opt,name=moq,proto3" json:"moq,omitempty"`
	StockQty     int32                  `protobuf:"varint,10,opt,name=stock_qty,json=stockQty,proto3" json:"stock_qty,omitempty"`
	LeadTimeDays int32                  `protobuf:"varint,11,opt,name=lead_time_days,json=leadTimeDays,proto3" json:"lead_time_days,omitempty"`
	DatasheetUrl string                 `protobuf:"bytes,12,opt,name=datasheet_url,json=datasheetUrl,proto3" json:"datasheet_url,omitempty"`
	// embedding is intentionally omitted — it's an infra concern, not part of
	// the public contract. The AI search service joins it server-side.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetNameZh() string {
	if x != nil {
		return x.NameZh
	}
	return ""
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetSpecs() *structpb.Struct {
	if x != nil {
		return x.Specs
	}
	return nil
}

func (x *Product) GetPriceUsd() float64 {
	if x != nil {
		return x.PriceUsd
	}
	return 0
}

func (x *Product) GetMoq() int32 {
	if x != nil {
		return x.Moq
	}
	return 0
}

func (x *Product) GetStockQty() int32 {
	if x != nil {
		return x.StockQty
	}
	return 0
}

func (x *Product) GetLeadTimeDays() int32 {
	if x != nil {
		return x.LeadTimeDays
	}
	return 0
}

func (x *Product) GetDatasheetUrl() string {
	if x != nil {
		return x.DatasheetUrl
	}
	return ""
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_product_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListProductsBySupplierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupplierId    string                 `protobuf:"bytes,1,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsBySupplierRequest) Reset() {
	*x = ListProductsBySupplierRequest{}
	mi := &file_product_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsBySupplierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsBySupplierRequest) ProtoMessage() {}

func (x *ListProductsBySupplierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsBySupplierRequest.ProtoReflect.Descriptor instead.
func (*ListProductsBySupplierRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductsBySupplierRequest) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *ListProductsBySupplierRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProductsBySupplierRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_product_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_product_v1_product_proto protoreflect.FileDescriptor

const file_product_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x18product/v1/product.proto\x12\n" +
	"product.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsupplier_id\x18\x02 \x01(\tR\n" +
	"supplierId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x17\n" +
	"\aname_zh\x18\x05 \x01(\tR\x06nameZh\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12-\n" +
	"\x05specs\x18\a \x01(\v2\x17.google.protobuf.StructR\x05specs\x12\x1b\n" +
	"\tprice_usd\x18\b \x01(\x01R\bpriceUsd\x12\x10\n" +
	"\x03moq\x18\t \x01(\x05R\x03moq\x12\x1b\n" +
	"\tstock_qty\x18\n" +
	" \x01(\x05R\bstockQty\x12$\n" +
	"\x0elead_time_days\x18\v \x01(\x05R\fleadTimeDays\x12#\n" +
	"\rdatasheet_url\x18\f \x01(\tR\fdatasheetUrl\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"E\n" +
	"\x14CreateProductRequest\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\x1dListProductsBySupplierRequest\x12\x1f\n" +
	"\vsupplier_id\x18\x01 \x01(\tR\n" +
	"supplierId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"]\n" +
	"\x14ListProductsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.v1.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xc0\x02\n" +
	"\x0eProductService\x12F\n" +
	"\rCreateProduct\x12 .product.v1.CreateProductRequest\x1a\x13.product.v1.Product\x12@\n" +
	"\n" +
	"GetProduct\x12\x1d.product.v1.GetProductRequest\x1a\x13.product.v1.Product\x12e\n" +
	"\x16ListProductsBySupplier\x12).product.v1.ListProductsBySupplierRequest\x1a .product.v1.ListProductsResponse\x12=\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBCZAgithub.com/nikitashilov/microblog_grpc/proto/product/v1;productv1b\x06proto3"

var (
	file_product_v1_product_proto_rawDescOnce sync.Once
	file_product_v1_product_proto_rawDescData []byte
)

func file_product_v1_product_proto_rawDescGZIP() []byte {
	file_product_v1_product_proto_rawDescOnce.Do(func() {
		file_product_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_v1_product_proto_rawDesc), len(file_product_v1_product_proto_rawDesc)))
	})
	return file_product_v1_product_proto_rawDescData
}

var file_product_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_product_v1_product_proto_goTypes = []any{
	(*Product)(nil),                       // 0: product.v1.Product
	(*CreateProductRequest)(nil),          // 1: product.v1.CreateProductRequest
	(*GetProductRequest)(nil),             // 2: product.v1.GetProductRequest
	(*ListProductsBySupplierRequest)(nil), // 3: product.v1.ListProductsBySupplierRequest
	(*ListProductsResponse)(nil),          // 4: product.v1.ListProductsResponse
	(*structpb.Struct)(nil),               // 5: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),         // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 7: google.protobuf.Empty
}
var file_product_v1_product_proto_depIdxs = []int32{
	5, // 0: product.v1.Product.specs:type_name -> google.protobuf.Struct
	6, // 1: product.v1.Product.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: product.v1.CreateProductRequest.product:type_name -> product.v1.Product
	0, // 3: product.v1.ListProductsResponse.products:type_name -> product.v1.Product
	1, // 4: product.v1.ProductService.CreateProduct:input_type -> product.v1.CreateProductRequest
	2, // 5: product.v1.ProductService.GetProduct:input_type -> product.v1.GetProductRequest
	3, // 6: product.v1.ProductService.ListProductsBySupplier:input_type -> product.v1.ListProductsBySupplierRequest
	7, // 7: product.v1.ProductService.HealthCheck:input_type -> google.protobuf.Empty
	0, // 8: product.v1.ProductService.CreateProduct:output_type -> product.v1.Product
	0, // 9: product.v1.ProductService.GetProduct:output_type -> product.v1.Product
	4, // 10: product.v1.ProductService.ListProductsBySupplier:output_type -> product.v1.ListProductsResponse
	7, // 11: product.v1.ProductService.HealthCheck:output_type -> google.protobuf.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_product_v1_product_proto_init() }
func file_product_v1_product_proto_init() {
	if File_product_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_v1_product_proto_rawDesc), len(file_product_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_v1_product_proto_goTypes,
		DependencyIndexes: file_product_v1_product_proto_depIdxs,
		MessageInfos:      file_product_v1_product_proto_msgTypes,
	}.Build()
	File_product_v1_product_proto = out.File
	file_product_v1_product_proto_goTypes = nil
	file_product_v1_product_proto_depIdxs = nil
}
