// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: design/v1/design.proto

package designv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A custom electronics part a startup is sourcing (PCB / PCBA / assembly).
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                          // PRJ-YYYYMMDD-NNNN
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // soft ref to users(id), role=startup
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"` // pcb | pcba | cable_assembly | enclosure | other
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`     // draft | active | archived
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OwnerEmail    string                 `protobuf:"bytes,9,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"` // denormalized for emails/UI (mirror RFQ)
	OwnerCompany  string                 `protobuf:"bytes,10,opt,name=owner_company,json=ownerCompany,proto3" json:"owner_company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_design_v1_design_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Project) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Project) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Project) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Project) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *Project) GetOwnerCompany() string {
	if x != nil {
		return x.OwnerCompany
	}
	return ""
}

// A file attached to a project. Committed only after ConfirmUpload; a row stays
// 'pending' until the client confirms the object-storage PUT succeeded.
type DesignFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // FILE-YYYYMMDD-NNNN
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // gerber | bom | assembly_drawing | pick_place | datasheet | nda | other
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`                                 // increments per (project_id, kind)
	ContentSha256 string                 `protobuf:"bytes,6,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"` // client-reported at confirm; integrity check
	ObjectKey     string                 `protobuf:"bytes,7,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`             // storage key; never exposed to clients directly
	SizeBytes     int64                  `protobuf:"varint,8,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType   string                 `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MIME
	UploadedBy    string                 `protobuf:"bytes,10,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`   // user id
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`                             // pending | committed
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesignFile) Reset() {
	*x = DesignFile{}
	mi := &file_design_v1_design_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesignFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesignFile) ProtoMessage() {}

func (x *DesignFile) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesignFile.ProtoReflect.Descriptor instead.
func (*DesignFile) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{1}
}

func (x *DesignFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DesignFile) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DesignFile) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DesignFile) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DesignFile) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DesignFile) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

func (x *DesignFile) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *DesignFile) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DesignFile) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DesignFile) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

func (x *DesignFile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DesignFile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Per-(project, manufacturer) NDA acceptance. Click-through for MVP; the row is
// the audit trail. A manufacturer needs status='accepted' before the service
// issues download URLs for a project's files.
type NDA struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ManufacturerId string                 `protobuf:"bytes,3,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"` // soft ref to users(id), role=manufacturer
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                       // pending | accepted
	NdaVersion     string                 `protobuf:"bytes,5,opt,name=nda_version,json=ndaVersion,proto3" json:"nda_version,omitempty"`             // which NDA text was accepted
	AcceptedIp     string                 `protobuf:"bytes,6,opt,name=accepted_ip,json=acceptedIp,proto3" json:"accepted_ip,omitempty"`             // captured at acceptance
	AcceptedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NDA) Reset() {
	*x = NDA{}
	mi := &file_design_v1_design_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NDA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NDA) ProtoMessage() {}

func (x *NDA) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NDA.ProtoReflect.Descriptor instead.
func (*NDA) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{2}
}

func (x *NDA) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NDA) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *NDA) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

func (x *NDA) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NDA) GetNdaVersion() string {
	if x != nil {
		return x.NdaVersion
	}
	return ""
}

func (x *NDA) GetAcceptedIp() string {
	if x != nil {
		return x.AcceptedIp
	}
	return ""
}

func (x *NDA) GetAcceptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcceptedAt
	}
	return nil
}

func (x *NDA) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"` // server assigns id/status/timestamps
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_design_v1_design_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProjectRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // gateway-passed; service enforces owner-or-NDA'd-manufacturer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_design_v1_design_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{4}
}

func (x *GetProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetProjectRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_design_v1_design_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{5}
}

func (x *ListProjectsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListProjectsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProjectsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListProjectsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_design_v1_design_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{6}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RequestUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // must be the project owner
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUploadURLRequest) Reset() {
	*x = RequestUploadURLRequest{}
	mi := &file_design_v1_design_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUploadURLRequest) ProtoMessage() {}

func (x *RequestUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUploadURLRequest.ProtoReflect.Descriptor instead.
func (*RequestUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{7}
}

func (x *RequestUploadURLRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RequestUploadURLRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *RequestUploadURLRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RequestUploadURLRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *RequestUploadURLRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// The presigned PUT the browser uploads to directly. Confirm afterward.
type UploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`          // pending DesignFile row
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"` // presigned PUT, short TTL
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	ExpiresInS    int32                  `protobuf:"varint,4,opt,name=expires_in_s,json=expiresInS,proto3" json:"expires_in_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadURLResponse) Reset() {
	*x = UploadURLResponse{}
	mi := &file_design_v1_design_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadURLResponse) ProtoMessage() {}

func (x *UploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadURLResponse.ProtoReflect.Descriptor instead.
func (*UploadURLResponse) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{8}
}

func (x *UploadURLResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadURLResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *UploadURLResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *UploadURLResponse) GetExpiresInS() int32 {
	if x != nil {
		return x.ExpiresInS
	}
	return 0
}

type ConfirmUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // must be the project owner
	ContentSha256 string                 `protobuf:"bytes,3,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadRequest) Reset() {
	*x = ConfirmUploadRequest{}
	mi := &file_design_v1_design_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadRequest) ProtoMessage() {}

func (x *ConfirmUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUploadRequest) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmUploadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ConfirmUploadRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ConfirmUploadRequest) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

func (x *ConfirmUploadRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // owner or NDA'd manufacturer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_design_v1_design_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{10}
}

func (x *ListFilesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListFilesRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*DesignFile          `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_design_v1_design_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{11}
}

func (x *ListFilesResponse) GetFiles() []*DesignFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type RequestDownloadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // owner, or manufacturer with an accepted NDA on the file's project
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDownloadURLRequest) Reset() {
	*x = RequestDownloadURLRequest{}
	mi := &file_design_v1_design_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDownloadURLRequest) ProtoMessage() {}

func (x *RequestDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*RequestDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{12}
}

func (x *RequestDownloadURLRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *RequestDownloadURLRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type DownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"` // presigned GET, short TTL
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ExpiresInS    int32                  `protobuf:"varint,3,opt,name=expires_in_s,json=expiresInS,proto3" json:"expires_in_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadURLResponse) Reset() {
	*x = DownloadURLResponse{}
	mi := &file_design_v1_design_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadURLResponse) ProtoMessage() {}

func (x *DownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadURLResponse.ProtoReflect.Descriptor instead.
func (*DownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{13}
}

func (x *DownloadURLResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *DownloadURLResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DownloadURLResponse) GetExpiresInS() int32 {
	if x != nil {
		return x.ExpiresInS
	}
	return 0
}

type AcceptNDARequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectId      string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ManufacturerId string                 `protobuf:"bytes,2,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	NdaVersion     string                 `protobuf:"bytes,3,opt,name=nda_version,json=ndaVersion,proto3" json:"nda_version,omitempty"`
	AcceptedIp     string                 `protobuf:"bytes,4,opt,name=accepted_ip,json=acceptedIp,proto3" json:"accepted_ip,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptNDARequest) Reset() {
	*x = AcceptNDARequest{}
	mi := &file_design_v1_design_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptNDARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptNDARequest) ProtoMessage() {}

func (x *AcceptNDARequest) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptNDARequest.ProtoReflect.Descriptor instead.
func (*AcceptNDARequest) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{14}
}

func (x *AcceptNDARequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AcceptNDARequest) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

func (x *AcceptNDARequest) GetNdaVersion() string {
	if x != nil {
		return x.NdaVersion
	}
	return ""
}

func (x *AcceptNDARequest) GetAcceptedIp() string {
	if x != nil {
		return x.AcceptedIp
	}
	return ""
}

type GetNDAStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectId      string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ManufacturerId string                 `protobuf:"bytes,2,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNDAStatusRequest) Reset() {
	*x = GetNDAStatusRequest{}
	mi := &file_design_v1_design_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNDAStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNDAStatusRequest) ProtoMessage() {}

func (x *GetNDAStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNDAStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNDAStatusRequest) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{15}
}

func (x *GetNDAStatusRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetNDAStatusRequest) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

// The project owner invites a manufacturer to a project (typically when creating
// an RFQ that references it). Creates a 'pending' NDA row — the invite. A
// manufacturer can only AcceptNDA after being invited, which closes the
// self-accept hole (a manufacturer can no longer accept an NDA on an arbitrary
// project id it happens to know).
type InviteManufacturerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectId      string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ManufacturerId string                 `protobuf:"bytes,2,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	ActorId        string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // must be the project owner
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InviteManufacturerRequest) Reset() {
	*x = InviteManufacturerRequest{}
	mi := &file_design_v1_design_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteManufacturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteManufacturerRequest) ProtoMessage() {}

func (x *InviteManufacturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_design_v1_design_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteManufacturerRequest.ProtoReflect.Descriptor instead.
func (*InviteManufacturerRequest) Descriptor() ([]byte, []int) {
	return file_design_v1_design_proto_rawDescGZIP(), []int{16}
}

func (x *InviteManufacturerRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *InviteManufacturerRequest) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

func (x *InviteManufacturerRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

var File_design_v1_design_proto protoreflect.FileDescriptor

const file_design_v1_design_proto_rawDesc = "" +
	"\n" +
	"\x16design/v1/design.proto\x12\tdesign.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x02\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vowner_email\x18\t \x01(\tR\n" +
	"ownerEmail\x12#\n" +
	"\rowner_company\x18\n" +
	" \x01(\tR\fownerCompany\"\x81\x03\n" +
	"\n" +
	"DesignFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x12%\n" +
	"\x0econtent_sha256\x18\x06 \x01(\tR\rcontentSha256\x12\x1d\n" +
	"\n" +
	"object_key\x18\a \x01(\tR\tobjectKey\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\b \x01(\x03R\tsizeBytes\x12!\n" +
	"\fcontent_type\x18\t \x01(\tR\vcontentType\x12\x1f\n" +
	"\vuploaded_by\x18\n" +
	" \x01(\tR\n" +
	"uploadedBy\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xaf\x02\n" +
	"\x03NDA\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12'\n" +
	"\x0fmanufacturer_id\x18\x03 \x01(\tR\x0emanufacturerId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vnda_version\x18\x05 \x01(\tR\n" +
	"ndaVersion\x12\x1f\n" +
	"\vaccepted_ip\x18\x06 \x01(\tR\n" +
	"acceptedIp\x12;\n" +
	"\vaccepted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"acceptedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"D\n" +
	"\x14CreateProjectRequest\x12,\n" +
	"\aproject\x18\x01 \x01(\v2\x12.design.v1.ProjectR\aproject\">\n" +
	"\x11GetProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\"v\n" +
	"\x13ListProjectsRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\\\n" +
	"\x14ListProjectsResponse\x12.\n" +
	"\bprojects\x18\x01 \x03(\v2\x12.design.v1.ProjectR\bprojects\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa6\x01\n" +
	"\x17RequestUploadURLRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\"\x8c\x01\n" +
	"\x11UploadURLResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\x12 \n" +
	"\fexpires_in_s\x18\x04 \x01(\x05R\n" +
	"expiresInS\"\x90\x01\n" +
	"\x14ConfirmUploadRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12%\n" +
	"\x0econtent_sha256\x18\x03 \x01(\tR\rcontentSha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"L\n" +
	"\x10ListFilesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\"@\n" +
	"\x11ListFilesResponse\x12+\n" +
	"\x05files\x18\x01 \x03(\v2\x15.design.v1.DesignFileR\x05files\"O\n" +
	"\x19RequestDownloadURLRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\"v\n" +
	"\x13DownloadURLResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12 \n" +
	"\fexpires_in_s\x18\x03 \x01(\x05R\n" +
	"expiresInS\"\x9c\x01\n" +
	"\x10AcceptNDARequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12'\n" +
	"\x0fmanufacturer_id\x18\x02 \x01(\tR\x0emanufacturerId\x12\x1f\n" +
	"\vnda_version\x18\x03 \x01(\tR\n" +
	"ndaVersion\x12\x1f\n" +
	"\vaccepted_ip\x18\x04 \x01(\tR\n" +
	"acceptedIp\"]\n" +
	"\x13GetNDAStatusRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12'\n" +
	"\x0fmanufacturer_id\x18\x02 \x01(\tR\x0emanufacturerId\"~\n" +
	"\x19InviteManufacturerRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12'\n" +
	"\x0fmanufacturer_id\x18\x02 \x01(\tR\x0emanufacturerId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId2\xae\x06\n" +
	"\rDesignService\x12J\n" +
	"\x12InviteManufacturer\x12$.design.v1.InviteManufacturerRequest\x1a\x0e.design.v1.NDA\x12D\n" +
	"\rCreateProject\x12\x1f.design.v1.CreateProjectRequest\x1a\x12.design.v1.Project\x12>\n" +
	"\n" +
	"GetProject\x12\x1c.design.v1.GetProjectRequest\x1a\x12.design.v1.Project\x12O\n" +
	"\fListProjects\x12\x1e.design.v1.ListProjectsRequest\x1a\x1f.design.v1.ListProjectsResponse\x12T\n" +
	"\x10RequestUploadURL\x12\".design.v1.RequestUploadURLRequest\x1a\x1c.design.v1.UploadURLResponse\x12G\n" +
	"\rConfirmUpload\x12\x1f.design.v1.ConfirmUploadRequest\x1a\x15.design.v1.DesignFile\x12F\n" +
	"\tListFiles\x12\x1b.design.v1.ListFilesRequest\x1a\x1c.design.v1.ListFilesResponse\x12Z\n" +
	"\x12RequestDownloadURL\x12$.design.v1.RequestDownloadURLRequest\x1a\x1e.design.v1.DownloadURLResponse\x128\n" +
	"\tAcceptNDA\x12\x1b.design.v1.AcceptNDARequest\x1a\x0e.design.v1.NDA\x12>\n" +
	"\fGetNDAStatus\x12\x1e.design.v1.GetNDAStatusRequest\x1a\x0e.design.v1.NDA\x12=\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBAZ?github.com/nikitashilov/microblog_grpc/proto/design/v1;designv1b\x06proto3"

var (
	file_design_v1_design_proto_rawDescOnce sync.Once
	file_design_v1_design_proto_rawDescData []byte
)

func file_design_v1_design_proto_rawDescGZIP() []byte {
	file_design_v1_design_proto_rawDescOnce.Do(func() {
		file_design_v1_design_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_design_v1_design_proto_rawDesc), len(file_design_v1_design_proto_rawDesc)))
	})
	return file_design_v1_design_proto_rawDescData
}

var file_design_v1_design_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_design_v1_design_proto_goTypes = []any{
	(*Project)(nil),                   // 0: design.v1.Project
	(*DesignFile)(nil),                // 1: design.v1.DesignFile
	(*NDA)(nil),                       // 2: design.v1.NDA
	(*CreateProjectRequest)(nil),      // 3: design.v1.CreateProjectRequest
	(*GetProjectRequest)(nil),         // 4: design.v1.GetProjectRequest
	(*ListProjectsRequest)(nil),       // 5: design.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),      // 6: design.v1.ListProjectsResponse
	(*RequestUploadURLRequest)(nil),   // 7: design.v1.RequestUploadURLRequest
	(*UploadURLResponse)(nil),         // 8: design.v1.UploadURLResponse
	(*ConfirmUploadRequest)(nil),      // 9: design.v1.ConfirmUploadRequest
	(*ListFilesRequest)(nil),          // 10: design.v1.ListFilesRequest
	(*ListFilesResponse)(nil),         // 11: design.v1.ListFilesResponse
	(*RequestDownloadURLRequest)(nil), // 12: design.v1.RequestDownloadURLRequest
	(*DownloadURLResponse)(nil),       // 13: design.v1.DownloadURLResponse
	(*AcceptNDARequest)(nil),          // 14: design.v1.AcceptNDARequest
	(*GetNDAStatusRequest)(nil),       // 15: design.v1.GetNDAStatusRequest
	(*InviteManufacturerRequest)(nil), // 16: design.v1.InviteManufacturerRequest
	(*timestamppb.Timestamp)(nil),     // 17: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 18: google.protobuf.Empty
}
var file_design_v1_design_proto_depIdxs = []int32{
	17, // 0: design.v1.Project.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: design.v1.Project.updated_at:type_name -> google.protobuf.Timestamp
	17, // 2: design.v1.DesignFile.created_at:type_name -> google.protobuf.Timestamp
	17, // 3: design.v1.NDA.accepted_at:type_name -> google.protobuf.Timestamp
	17, // 4: design.v1.NDA.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: design.v1.CreateProjectRequest.project:type_name -> design.v1.Project
	0,  // 6: design.v1.ListProjectsResponse.projects:type_name -> design.v1.Project
	1,  // 7: design.v1.ListFilesResponse.files:type_name -> design.v1.DesignFile
	16, // 8: design.v1.DesignService.InviteManufacturer:input_type -> design.v1.InviteManufacturerRequest
	3,  // 9: design.v1.DesignService.CreateProject:input_type -> design.v1.CreateProjectRequest
	4,  // 10: design.v1.DesignService.GetProject:input_type -> design.v1.GetProjectRequest
	5,  // 11: design.v1.DesignService.ListProjects:input_type -> design.v1.ListProjectsRequest
	7,  // 12: design.v1.DesignService.RequestUploadURL:input_type -> design.v1.RequestUploadURLRequest
	9,  // 13: design.v1.DesignService.ConfirmUpload:input_type -> design.v1.ConfirmUploadRequest
	10, // 14: design.v1.DesignService.ListFiles:input_type -> design.v1.ListFilesRequest
	12, // 15: design.v1.DesignService.RequestDownloadURL:input_type -> design.v1.RequestDownloadURLRequest
	14, // 16: design.v1.DesignService.AcceptNDA:input_type -> design.v1.AcceptNDARequest
	15, // 17: design.v1.DesignService.GetNDAStatus:input_type -> design.v1.GetNDAStatusRequest
	18, // 18: design.v1.DesignService.HealthCheck:input_type -> google.protobuf.Empty
	2,  // 19: design.v1.DesignService.InviteManufacturer:output_type -> design.v1.NDA
	0,  // 20: design.v1.DesignService.CreateProject:output_type -> design.v1.Project
	0,  // 21: design.v1.DesignService.GetProject:output_type -> design.v1.Project
	6,  // 22: design.v1.DesignService.ListProjects:output_type -> design.v1.ListProjectsResponse
	8,  // 23: design.v1.DesignService.RequestUploadURL:output_type -> design.v1.UploadURLResponse
	1,  // 24: design.v1.DesignService.ConfirmUpload:output_type -> design.v1.DesignFile
	11, // 25: design.v1.DesignService.ListFiles:output_type -> design.v1.ListFilesResponse
	13, // 26: design.v1.DesignService.RequestDownloadURL:output_type -> design.v1.DownloadURLResponse
	2,  // 27: design.v1.DesignService.AcceptNDA:output_type -> design.v1.NDA
	2,  // 28: design.v1.DesignService.GetNDAStatus:output_type -> design.v1.NDA
	18, // 29: design.v1.DesignService.HealthCheck:output_type -> google.protobuf.Empty
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_design_v1_design_proto_init() }
func file_design_v1_design_proto_init() {
	if File_design_v1_design_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_design_v1_design_proto_rawDesc), len(file_design_v1_design_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_design_v1_design_proto_goTypes,
		DependencyIndexes: file_design_v1_design_proto_depIdxs,
		MessageInfos:      file_design_v1_design_proto_msgTypes,
	}.Build()
	File_design_v1_design_proto = out.File
	file_design_v1_design_proto_goTypes = nil
	file_design_v1_design_proto_depIdxs = nil
}
