// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: design/v1/design.proto

package designv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DesignService_InviteManufacturer_FullMethodName = "/design.v1.DesignService/InviteManufacturer"
	DesignService_CreateProject_FullMethodName      = "/design.v1.DesignService/CreateProject"
	DesignService_GetProject_FullMethodName         = "/design.v1.DesignService/GetProject"
	DesignService_ListProjects_FullMethodName       = "/design.v1.DesignService/ListProjects"
	DesignService_RequestUploadURL_FullMethodName   = "/design.v1.DesignService/RequestUploadURL"
	DesignService_ConfirmUpload_FullMethodName      = "/design.v1.DesignService/ConfirmUpload"
	DesignService_ListFiles_FullMethodName          = "/design.v1.DesignService/ListFiles"
	DesignService_RequestDownloadURL_FullMethodName = "/design.v1.DesignService/RequestDownloadURL"
	DesignService_AcceptNDA_FullMethodName          = "/design.v1.DesignService/AcceptNDA"
	DesignService_GetNDAStatus_FullMethodName       = "/design.v1.DesignService/GetNDAStatus"
	DesignService_HealthCheck_FullMethodName        = "/design.v1.DesignService/HealthCheck"
)

// DesignServiceClient is the client API for DesignService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DesignServiceClient interface {
	InviteManufacturer(ctx context.Context, in *InviteManufacturerRequest, opts ...grpc.CallOption) (*NDA, error)
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*Project, error)
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	RequestUploadURL(ctx context.Context, in *RequestUploadURLRequest, opts ...grpc.CallOption) (*UploadURLResponse, error)
	ConfirmUpload(ctx context.Context, in *ConfirmUploadRequest, opts ...grpc.CallOption) (*DesignFile, error)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	RequestDownloadURL(ctx context.Context, in *RequestDownloadURLRequest, opts ...grpc.CallOption) (*DownloadURLResponse, error)
	AcceptNDA(ctx context.Context, in *AcceptNDARequest, opts ...grpc.CallOption) (*NDA, error)
	GetNDAStatus(ctx context.Context, in *GetNDAStatusRequest, opts ...grpc.CallOption) (*NDA, error)
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type designServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDesignServiceClient(cc grpc.ClientConnInterface) DesignServiceClient {
	return &designServiceClient{cc}
}

func (c *designServiceClient) InviteManufacturer(ctx context.Context, in *InviteManufacturerRequest, opts ...grpc.CallOption) (*NDA, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NDA)
	err := c.cc.Invoke(ctx, DesignService_InviteManufacturer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, DesignService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, DesignService_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, DesignService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) RequestUploadURL(ctx context.Context, in *RequestUploadURLRequest, opts ...grpc.CallOption) (*UploadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadURLResponse)
	err := c.cc.Invoke(ctx, DesignService_RequestUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) ConfirmUpload(ctx context.Context, in *ConfirmUploadRequest, opts ...grpc.CallOption) (*DesignFile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignFile)
	err := c.cc.Invoke(ctx, DesignService_ConfirmUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, DesignService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) RequestDownloadURL(ctx context.Context, in *RequestDownloadURLRequest, opts ...grpc.CallOption) (*DownloadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadURLResponse)
	err := c.cc.Invoke(ctx, DesignService_RequestDownloadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) AcceptNDA(ctx context.Context, in *AcceptNDARequest, opts ...grpc.CallOption) (*NDA, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NDA)
	err := c.cc.Invoke(ctx, DesignService_AcceptNDA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) GetNDAStatus(ctx context.Context, in *GetNDAStatusRequest, opts ...grpc.CallOption) (*NDA, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NDA)
	err := c.cc.Invoke(ctx, DesignService_GetNDAStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *designServiceClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DesignService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DesignServiceServer is the server API for DesignService service.
// All implementations must embed UnimplementedDesignServiceServer
// for forward compatibility.
type DesignServiceServer interface {
	InviteManufacturer(context.Context, *InviteManufacturerRequest) (*NDA, error)
	CreateProject(context.Context, *CreateProjectRequest) (*Project, error)
	GetProject(context.Context, *GetProjectRequest) (*Project, error)
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	RequestUploadURL(context.Context, *RequestUploadURLRequest) (*UploadURLResponse, error)
	ConfirmUpload(context.Context, *ConfirmUploadRequest) (*DesignFile, error)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	RequestDownloadURL(context.Context, *RequestDownloadURLRequest) (*DownloadURLResponse, error)
	AcceptNDA(context.Context, *AcceptNDARequest) (*NDA, error)
	GetNDAStatus(context.Context, *GetNDAStatusRequest) (*NDA, error)
	HealthCheck(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedDesignServiceServer()
}

// UnimplementedDesignServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDesignServiceServer struct{}

func (UnimplementedDesignServiceServer) InviteManufacturer(context.Context, *InviteManufacturerRequest) (*NDA, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteManufacturer not implemented")
}
func (UnimplementedDesignServiceServer) CreateProject(context.Context, *CreateProjectRequest) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedDesignServiceServer) GetProject(context.Context, *GetProjectRequest) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedDesignServiceServer) ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedDesignServiceServer) RequestUploadURL(context.Context, *RequestUploadURLRequest) (*UploadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestUploadURL not implemented")
}
func (UnimplementedDesignServiceServer) ConfirmUpload(context.Context, *ConfirmUploadRequest) (*DesignFile, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmUpload not implemented")
}
func (UnimplementedDesignServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedDesignServiceServer) RequestDownloadURL(context.Context, *RequestDownloadURLRequest) (*DownloadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestDownloadURL not implemented")
}
func (UnimplementedDesignServiceServer) AcceptNDA(context.Context, *AcceptNDARequest) (*NDA, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptNDA not implemented")
}
func (UnimplementedDesignServiceServer) GetNDAStatus(context.Context, *GetNDAStatusRequest) (*NDA, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNDAStatus not implemented")
}
func (UnimplementedDesignServiceServer) HealthCheck(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDesignServiceServer) mustEmbedUnimplementedDesignServiceServer() {}
func (UnimplementedDesignServiceServer) testEmbeddedByValue()                       {}

// UnsafeDesignServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DesignServiceServer will
// result in compilation errors.
type UnsafeDesignServiceServer interface {
	mustEmbedUnimplementedDesignServiceServer()
}

func RegisterDesignServiceServer(s grpc.ServiceRegistrar, srv DesignServiceServer) {
	// If the following call panics, it indicates UnimplementedDesignServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DesignService_ServiceDesc, srv)
}

func _DesignService_InviteManufacturer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteManufacturerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).InviteManufacturer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_InviteManufacturer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).InviteManufacturer(ctx, req.(*InviteManufacturerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_RequestUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUploadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).RequestUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_RequestUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).RequestUploadURL(ctx, req.(*RequestUploadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_ConfirmUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).ConfirmUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_ConfirmUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).ConfirmUpload(ctx, req.(*ConfirmUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_RequestDownloadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDownloadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).RequestDownloadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_RequestDownloadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).RequestDownloadURL(ctx, req.(*RequestDownloadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_AcceptNDA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptNDARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).AcceptNDA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_AcceptNDA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).AcceptNDA(ctx, req.(*AcceptNDARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_GetNDAStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNDAStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).GetNDAStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_GetNDAStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).GetNDAStatus(ctx, req.(*GetNDAStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesignService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesignServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesignService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesignServiceServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DesignService_ServiceDesc is the grpc.ServiceDesc for DesignService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DesignService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "design.v1.DesignService",
	HandlerType: (*DesignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InviteManufacturer",
			Handler:    _DesignService_InviteManufacturer_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _DesignService_CreateProject_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _DesignService_GetProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _DesignService_ListProjects_Handler,
		},
		{
			MethodName: "RequestUploadURL",
			Handler:    _DesignService_RequestUploadURL_Handler,
		},
		{
			MethodName: "ConfirmUpload",
			Handler:    _DesignService_ConfirmUpload_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _DesignService_ListFiles_Handler,
		},
		{
			MethodName: "RequestDownloadURL",
			Handler:    _DesignService_RequestDownloadURL_Handler,
		},
		{
			MethodName: "AcceptNDA",
			Handler:    _DesignService_AcceptNDA_Handler,
		},
		{
			MethodName: "GetNDAStatus",
			Handler:    _DesignService_GetNDAStatus_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DesignService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "design/v1/design.proto",
}
