// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rfq/v1/rfq.proto

package rfqv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RFQ struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                          // RFQ-YYYYMMDD-NNNN-SZX
	BuyerId           string                 `protobuf:"bytes,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"` // soft ref to users(id) in user-service
	QueryText         string                 `protobuf:"bytes,3,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	ParsedSpecs       *structpb.Struct       `protobuf:"bytes,4,opt,name=parsed_specs,json=parsedSpecs,proto3" json:"parsed_specs,omitempty"`
	MatchedProductIds []string               `protobuf:"bytes,5,rep,name=matched_product_ids,json=matchedProductIds,proto3" json:"matched_product_ids,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // open | quoted | accepted | closed
	Qty               int32                  `protobuf:"varint,7,opt,name=qty,proto3" json:"qty,omitempty"`
	TargetDate        string                 `protobuf:"bytes,8,opt,name=target_date,json=targetDate,proto3" json:"target_date,omitempty"` // ISO-8601 date
	ShippingAddress   string                 `protobuf:"bytes,9,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Notes             string                 `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RFQ) Reset() {
	*x = RFQ{}
	mi := &file_rfq_v1_rfq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RFQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RFQ) ProtoMessage() {}

func (x *RFQ) ProtoReflect() protoreflect.Message {
	mi := &file_rfq_v1_rfq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RFQ.ProtoReflect.Descriptor instead.
func (*RFQ) Descriptor() ([]byte, []int) {
	return file_rfq_v1_rfq_proto_rawDescGZIP(), []int{0}
}

func (x *RFQ) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RFQ) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *RFQ) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *RFQ) GetParsedSpecs() *structpb.Struct {
	if x != nil {
		return x.ParsedSpecs
	}
	return nil
}

func (x *RFQ) GetMatchedProductIds() []string {
	if x != nil {
		return x.MatchedProductIds
	}
	return nil
}

func (x *RFQ) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RFQ) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *RFQ) GetTargetDate() string {
	if x != nil {
		return x.TargetDate
	}
	return ""
}

func (x *RFQ) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

func (x *RFQ) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *RFQ) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Quote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // QUOTE-YYYYMMDD-NNNN-SZX
	RfqId         string                 `protobuf:"bytes,2,opt,name=rfq_id,json=rfqId,proto3" json:"rfq_id,omitempty"`
	SupplierId    string                 `protobuf:"bytes,3,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // optional
	PriceUsd      float64                `protobuf:"fixed64,5,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	LeadTimeDays  int32                  `protobuf:"varint,6,opt,name=lead_time_days,json=leadTimeDays,proto3" json:"lead_time_days,omitempty"`
	ValidityDate  string                 `protobuf:"bytes,7,opt,name=validity_date,json=validityDate,proto3" json:"validity_date,omitempty"` // ISO-8601 date
	SupplierNotes string                 `protobuf:"bytes,8,opt,name=supplier_notes,json=supplierNotes,proto3" json:"supplier_notes,omitempty"`
	MatchScore    int32                  `protobuf:"varint,9,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"` // 0..100, AI-generated
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`                           // pending | submitted | accepted | rejected
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_rfq_v1_rfq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_rfq_v1_rfq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_rfq_v1_rfq_proto_rawDescGZIP(), []int{1}
}

func (x *Quote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quote) GetRfqId() string {
	if x != nil {
		return x.RfqId
	}
	return ""
}

func (x *Quote) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *Quote) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Quote) GetPriceUsd() float64 {
	if x != nil {
		return x.PriceUsd
	}
	return 0
}

func (x *Quote) GetLeadTimeDays() int32 {
	if x != nil {
		return x.LeadTimeDays
	}
	return 0
}

func (x *Quote) GetValidityDate() string {
	if x != nil {
		return x.ValidityDate
	}
	return ""
}

func (x *Quote) GetSupplierNotes() string {
	if x != nil {
		return x.SupplierNotes
	}
	return ""
}

func (x *Quote) GetMatchScore() int32 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

func (x *Quote) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Quote) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *Quote) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateRFQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rfq           *RFQ                   `protobuf:"bytes,1,opt,name=rfq,proto3" json:"rfq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRFQRequest) Reset() {
	*x = CreateRFQRequest{}
	mi := &file_rfq_v1_rfq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRFQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRFQRequest) ProtoMessage() {}

func (x *CreateRFQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rfq_v1_rfq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRFQRequest.ProtoReflect.Descriptor instead.
func (*CreateRFQRequest) Descriptor() ([]byte, []int) {
	return file_rfq_v1_rfq_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRFQRequest) GetRfq() *RFQ {
	if x != nil {
		return x.Rfq
	}
	return nil
}

type GetRFQRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestingUserId string                 `protobuf:"bytes,2,opt,name=requesting_user_id,json=requestingUserId,proto3" json:"requesting_user_id,omitempty"` // gateway-passed; service enforces authz
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRFQRequest) Reset() {
	*x = GetRFQRequest{}
	mi := &file_rfq_v1_rfq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRFQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRFQRequest) ProtoMessage() {}

func (x *GetRFQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rfq_v1_rfq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRFQRequest.ProtoReflect.Descriptor instead.
func (*GetRFQRequest) Descriptor() ([]byte, []int) {
	return file_rfq_v1_rfq_proto_rawDescGZIP(), []int{3}
}

func (x *GetRFQRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRFQRequest) GetRequestingUserId() string {
	if x != nil {
		return x.RequestingUserId
	}
	return ""
}

type ListRFQsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerId       string                 `protobuf:"bytes,1,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRFQsRequest) Reset() {
	*x = ListRFQsRequest{}
	mi := &file_rfq_v1_rfq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRFQsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRFQsRequest) ProtoMessage() {}

func (x *ListRFQsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rfq_v1_rfq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRFQsRequest.ProtoReflect.Descriptor instead.
func (*ListRFQsRequest) Descriptor() ([]byte, []int) {
	return file_rfq_v1_rfq_proto_rawDescGZIP(), []int{4}
}

func (x *ListRFQsRequest) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *ListRFQsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRFQsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRFQsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListRFQsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rfqs          []*RFQ                 `protobuf:"bytes,1,rep,name=rfqs,proto3" json:"rfqs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRFQsResponse) Reset() {
	*x = ListRFQsResponse{}
	mi := &file_rfq_v1_rfq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRFQsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRFQsResponse) ProtoMessage() {}

func (x *ListRFQsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rfq_v1_rfq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRFQsResponse.ProtoReflect.Descriptor instead.
func (*ListRFQsResponse) Descriptor() ([]byte, []int) {
	return file_rfq_v1_rfq_proto_rawDescGZIP(), []int{5}
}

func (x *ListRFQsResponse) GetRfqs() []*RFQ {
	if x != nil {
		return x.Rfqs
	}
	return nil
}

func (x *ListRFQsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AddQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quote         *Quote                 `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddQuoteRequest) Reset() {
	*x = AddQuoteRequest{}
	mi := &file_rfq_v1_rfq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQuoteRequest) ProtoMessage() {}

func (x *AddQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rfq_v1_rfq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQuoteRequest.ProtoReflect.Descriptor instead.
func (*AddQuoteRequest) Descriptor() ([]byte, []int) {
	return file_rfq_v1_rfq_proto_rawDescGZIP(), []int{6}
}

func (x *AddQuoteRequest) GetQuote() *Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

type ListQuotesForRFQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RfqId         string                 `protobuf:"bytes,1,opt,name=rfq_id,json=rfqId,proto3" json:"rfq_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuotesForRFQRequest) Reset() {
	*x = ListQuotesForRFQRequest{}
	mi := &file_rfq_v1_rfq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotesForRFQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotesForRFQRequest) ProtoMessage() {}

func (x *ListQuotesForRFQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rfq_v1_rfq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotesForRFQRequest.ProtoReflect.Descriptor instead.
func (*ListQuotesForRFQRequest) Descriptor() ([]byte, []int) {
	return file_rfq_v1_rfq_proto_rawDescGZIP(), []int{7}
}

func (x *ListQuotesForRFQRequest) GetRfqId() string {
	if x != nil {
		return x.RfqId
	}
	return ""
}

type ListQuotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotes        []*Quote               `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuotesResponse) Reset() {
	*x = ListQuotesResponse{}
	mi := &file_rfq_v1_rfq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotesResponse) ProtoMessage() {}

func (x *ListQuotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rfq_v1_rfq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotesResponse.ProtoReflect.Descriptor instead.
func (*ListQuotesResponse) Descriptor() ([]byte, []int) {
	return file_rfq_v1_rfq_proto_rawDescGZIP(), []int{8}
}

func (x *ListQuotesResponse) GetQuotes() []*Quote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

var File_rfq_v1_rfq_proto protoreflect.FileDescriptor

const file_rfq_v1_rfq_proto_rawDesc = "" +
	"\n" +
	"\x10rfq/v1/rfq.proto\x12\x06rfq.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x03\n" +
	"\x03RFQ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\tR\abuyerId\x12\x1d\n" +
	"\n" +
	"query_text\x18\x03 \x01(\tR\tqueryText\x12:\n" +
	"\fparsed_specs\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vparsedSpecs\x12.\n" +
	"\x13matched_product_ids\x18\x05 \x03(\tR\x11matchedProductIds\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x10\n" +
	"\x03qty\x18\a \x01(\x05R\x03qty\x12\x1f\n" +
	"\vtarget_date\x18\b \x01(\tR\n" +
	"targetDate\x12)\n" +
	"\x10shipping_address\x18\t \x01(\tR\x0fshippingAddress\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb0\x03\n" +
	"\x05Quote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06rfq_id\x18\x02 \x01(\tR\x05rfqId\x12\x1f\n" +
	"\vsupplier_id\x18\x03 \x01(\tR\n" +
	"supplierId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\x12\x1b\n" +
	"\tprice_usd\x18\x05 \x01(\x01R\bpriceUsd\x12$\n" +
	"\x0elead_time_days\x18\x06 \x01(\x05R\fleadTimeDays\x12#\n" +
	"\rvalidity_date\x18\a \x01(\tR\fvalidityDate\x12%\n" +
	"\x0esupplier_notes\x18\b \x01(\tR\rsupplierNotes\x12\x1f\n" +
	"\vmatch_score\x18\t \x01(\x05R\n" +
	"matchScore\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12=\n" +
	"\fsubmitted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"1\n" +
	"\x10CreateRFQRequest\x12\x1d\n" +
	"\x03rfq\x18\x01 \x01(\v2\v.rfq.v1.RFQR\x03rfq\"M\n" +
	"\rGetRFQRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12requesting_user_id\x18\x02 \x01(\tR\x10requestingUserId\"r\n" +
	"\x0fListRFQsRequest\x12\x19\n" +
	"\bbuyer_id\x18\x01 \x01(\tR\abuyerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"I\n" +
	"\x10ListRFQsResponse\x12\x1f\n" +
	"\x04rfqs\x18\x01 \x03(\v2\v.rfq.v1.RFQR\x04rfqs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"6\n" +
	"\x0fAddQuoteRequest\x12#\n" +
	"\x05quote\x18\x01 \x01(\v2\r.rfq.v1.QuoteR\x05quote\"0\n" +
	"\x17ListQuotesForRFQRequest\x12\x15\n" +
	"\x06rfq_id\x18\x01 \x01(\tR\x05rfqId\";\n" +
	"\x12ListQuotesResponse\x12%\n" +
	"\x06quotes\x18\x01 \x03(\v2\r.rfq.v1.QuoteR\x06quotes2\xf1\x02\n" +
	"\n" +
	"RFQService\x122\n" +
	"\tCreateRFQ\x12\x18.rfq.v1.CreateRFQRequest\x1a\v.rfq.v1.RFQ\x12,\n" +
	"\x06GetRFQ\x12\x15.rfq.v1.GetRFQRequest\x1a\v.rfq.v1.RFQ\x12=\n" +
	"\bListRFQs\x12\x17.rfq.v1.ListRFQsRequest\x1a\x18.rfq.v1.ListRFQsResponse\x122\n" +
	"\bAddQuote\x12\x17.rfq.v1.AddQuoteRequest\x1a\r.rfq.v1.Quote\x12O\n" +
	"\x10ListQuotesForRFQ\x12\x1f.rfq.v1.ListQuotesForRFQRequest\x1a\x1a.rfq.v1.ListQuotesResponse\x12=\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB;Z9github.com/nikitashilov/microblog_grpc/proto/rfq/v1;rfqv1b\x06proto3"

var (
	file_rfq_v1_rfq_proto_rawDescOnce sync.Once
	file_rfq_v1_rfq_proto_rawDescData []byte
)

func file_rfq_v1_rfq_proto_rawDescGZIP() []byte {
	file_rfq_v1_rfq_proto_rawDescOnce.Do(func() {
		file_rfq_v1_rfq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rfq_v1_rfq_proto_rawDesc), len(file_rfq_v1_rfq_proto_rawDesc)))
	})
	return file_rfq_v1_rfq_proto_rawDescData
}

var file_rfq_v1_rfq_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rfq_v1_rfq_proto_goTypes = []any{
	(*RFQ)(nil),                     // 0: rfq.v1.RFQ
	(*Quote)(nil),                   // 1: rfq.v1.Quote
	(*CreateRFQRequest)(nil),        // 2: rfq.v1.CreateRFQRequest
	(*GetRFQRequest)(nil),           // 3: rfq.v1.GetRFQRequest
	(*ListRFQsRequest)(nil),         // 4: rfq.v1.ListRFQsRequest
	(*ListRFQsResponse)(nil),        // 5: rfq.v1.ListRFQsResponse
	(*AddQuoteRequest)(nil),         // 6: rfq.v1.AddQuoteRequest
	(*ListQuotesForRFQRequest)(nil), // 7: rfq.v1.ListQuotesForRFQRequest
	(*ListQuotesResponse)(nil),      // 8: rfq.v1.ListQuotesResponse
	(*structpb.Struct)(nil),         // 9: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 11: google.protobuf.Empty
}
var file_rfq_v1_rfq_proto_depIdxs = []int32{
	9,  // 0: rfq.v1.RFQ.parsed_specs:type_name -> google.protobuf.Struct
	10, // 1: rfq.v1.RFQ.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: rfq.v1.Quote.submitted_at:type_name -> google.protobuf.Timestamp
	10, // 3: rfq.v1.Quote.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: rfq.v1.CreateRFQRequest.rfq:type_name -> rfq.v1.RFQ
	0,  // 5: rfq.v1.ListRFQsResponse.rfqs:type_name -> rfq.v1.RFQ
	1,  // 6: rfq.v1.AddQuoteRequest.quote:type_name -> rfq.v1.Quote
	1,  // 7: rfq.v1.ListQuotesResponse.quotes:type_name -> rfq.v1.Quote
	2,  // 8: rfq.v1.RFQService.CreateRFQ:input_type -> rfq.v1.CreateRFQRequest
	3,  // 9: rfq.v1.RFQService.GetRFQ:input_type -> rfq.v1.GetRFQRequest
	4,  // 10: rfq.v1.RFQService.ListRFQs:input_type -> rfq.v1.ListRFQsRequest
	6,  // 11: rfq.v1.RFQService.AddQuote:input_type -> rfq.v1.AddQuoteRequest
	7,  // 12: rfq.v1.RFQService.ListQuotesForRFQ:input_type -> rfq.v1.ListQuotesForRFQRequest
	11, // 13: rfq.v1.RFQService.HealthCheck:input_type -> google.protobuf.Empty
	0,  // 14: rfq.v1.RFQService.CreateRFQ:output_type -> rfq.v1.RFQ
	0,  // 15: rfq.v1.RFQService.GetRFQ:output_type -> rfq.v1.RFQ
	5,  // 16: rfq.v1.RFQService.ListRFQs:output_type -> rfq.v1.ListRFQsResponse
	1,  // 17: rfq.v1.RFQService.AddQuote:output_type -> rfq.v1.Quote
	8,  // 18: rfq.v1.RFQService.ListQuotesForRFQ:output_type -> rfq.v1.ListQuotesResponse
	11, // 19: rfq.v1.RFQService.HealthCheck:output_type -> google.protobuf.Empty
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_rfq_v1_rfq_proto_init() }
func file_rfq_v1_rfq_proto_init() {
	if File_rfq_v1_rfq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rfq_v1_rfq_proto_rawDesc), len(file_rfq_v1_rfq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rfq_v1_rfq_proto_goTypes,
		DependencyIndexes: file_rfq_v1_rfq_proto_depIdxs,
		MessageInfos:      file_rfq_v1_rfq_proto_msgTypes,
	}.Build()
	File_rfq_v1_rfq_proto = out.File
	file_rfq_v1_rfq_proto_goTypes = nil
	file_rfq_v1_rfq_proto_depIdxs = nil
}
