// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: rfq/v1/rfq.proto

package rfqv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RFQService_CreateRFQ_FullMethodName        = "/rfq.v1.RFQService/CreateRFQ"
	RFQService_GetRFQ_FullMethodName           = "/rfq.v1.RFQService/GetRFQ"
	RFQService_ListRFQs_FullMethodName         = "/rfq.v1.RFQService/ListRFQs"
	RFQService_AddQuote_FullMethodName         = "/rfq.v1.RFQService/AddQuote"
	RFQService_ListQuotesForRFQ_FullMethodName = "/rfq.v1.RFQService/ListQuotesForRFQ"
	RFQService_HealthCheck_FullMethodName      = "/rfq.v1.RFQService/HealthCheck"
)

// RFQServiceClient is the client API for RFQService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RFQServiceClient interface {
	CreateRFQ(ctx context.Context, in *CreateRFQRequest, opts ...grpc.CallOption) (*RFQ, error)
	GetRFQ(ctx context.Context, in *GetRFQRequest, opts ...grpc.CallOption) (*RFQ, error)
	ListRFQs(ctx context.Context, in *ListRFQsRequest, opts ...grpc.CallOption) (*ListRFQsResponse, error)
	AddQuote(ctx context.Context, in *AddQuoteRequest, opts ...grpc.CallOption) (*Quote, error)
	ListQuotesForRFQ(ctx context.Context, in *ListQuotesForRFQRequest, opts ...grpc.CallOption) (*ListQuotesResponse, error)
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type rFQServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRFQServiceClient(cc grpc.ClientConnInterface) RFQServiceClient {
	return &rFQServiceClient{cc}
}

func (c *rFQServiceClient) CreateRFQ(ctx context.Context, in *CreateRFQRequest, opts ...grpc.CallOption) (*RFQ, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RFQ)
	err := c.cc.Invoke(ctx, RFQService_CreateRFQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rFQServiceClient) GetRFQ(ctx context.Context, in *GetRFQRequest, opts ...grpc.CallOption) (*RFQ, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RFQ)
	err := c.cc.Invoke(ctx, RFQService_GetRFQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rFQServiceClient) ListRFQs(ctx context.Context, in *ListRFQsRequest, opts ...grpc.CallOption) (*ListRFQsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRFQsResponse)
	err := c.cc.Invoke(ctx, RFQService_ListRFQs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rFQServiceClient) AddQuote(ctx context.Context, in *AddQuoteRequest, opts ...grpc.CallOption) (*Quote, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Quote)
	err := c.cc.Invoke(ctx, RFQService_AddQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rFQServiceClient) ListQuotesForRFQ(ctx context.Context, in *ListQuotesForRFQRequest, opts ...grpc.CallOption) (*ListQuotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQuotesResponse)
	err := c.cc.Invoke(ctx, RFQService_ListQuotesForRFQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rFQServiceClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RFQService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RFQServiceServer is the server API for RFQService service.
// All implementations must embed UnimplementedRFQServiceServer
// for forward compatibility.
type RFQServiceServer interface {
	CreateRFQ(context.Context, *CreateRFQRequest) (*RFQ, error)
	GetRFQ(context.Context, *GetRFQRequest) (*RFQ, error)
	ListRFQs(context.Context, *ListRFQsRequest) (*ListRFQsResponse, error)
	AddQuote(context.Context, *AddQuoteRequest) (*Quote, error)
	ListQuotesForRFQ(context.Context, *ListQuotesForRFQRequest) (*ListQuotesResponse, error)
	HealthCheck(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedRFQServiceServer()
}

// UnimplementedRFQServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRFQServiceServer struct{}

func (UnimplementedRFQServiceServer) CreateRFQ(context.Context, *CreateRFQRequest) (*RFQ, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRFQ not implemented")
}
func (UnimplementedRFQServiceServer) GetRFQ(context.Context, *GetRFQRequest) (*RFQ, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRFQ not implemented")
}
func (UnimplementedRFQServiceServer) ListRFQs(context.Context, *ListRFQsRequest) (*ListRFQsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRFQs not implemented")
}
func (UnimplementedRFQServiceServer) AddQuote(context.Context, *AddQuoteRequest) (*Quote, error) {
	return nil, status.Error(codes.Unimplemented, "method AddQuote not implemented")
}
func (UnimplementedRFQServiceServer) ListQuotesForRFQ(context.Context, *ListQuotesForRFQRequest) (*ListQuotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQuotesForRFQ not implemented")
}
func (UnimplementedRFQServiceServer) HealthCheck(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRFQServiceServer) mustEmbedUnimplementedRFQServiceServer() {}
func (UnimplementedRFQServiceServer) testEmbeddedByValue()                    {}

// UnsafeRFQServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RFQServiceServer will
// result in compilation errors.
type UnsafeRFQServiceServer interface {
	mustEmbedUnimplementedRFQServiceServer()
}

func RegisterRFQServiceServer(s grpc.ServiceRegistrar, srv RFQServiceServer) {
	// If the following call panics, it indicates UnimplementedRFQServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RFQService_ServiceDesc, srv)
}

func _RFQService_CreateRFQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRFQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RFQServiceServer).CreateRFQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RFQService_CreateRFQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RFQServiceServer).CreateRFQ(ctx, req.(*CreateRFQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RFQService_GetRFQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRFQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RFQServiceServer).GetRFQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RFQService_GetRFQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RFQServiceServer).GetRFQ(ctx, req.(*GetRFQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RFQService_ListRFQs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRFQsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RFQServiceServer).ListRFQs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RFQService_ListRFQs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RFQServiceServer).ListRFQs(ctx, req.(*ListRFQsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RFQService_AddQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RFQServiceServer).AddQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RFQService_AddQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RFQServiceServer).AddQuote(ctx, req.(*AddQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RFQService_ListQuotesForRFQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQuotesForRFQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RFQServiceServer).ListQuotesForRFQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RFQService_ListQuotesForRFQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RFQServiceServer).ListQuotesForRFQ(ctx, req.(*ListQuotesForRFQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RFQService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RFQServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RFQService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RFQServiceServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RFQService_ServiceDesc is the grpc.ServiceDesc for RFQService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RFQService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rfq.v1.RFQService",
	HandlerType: (*RFQServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRFQ",
			Handler:    _RFQService_CreateRFQ_Handler,
		},
		{
			MethodName: "GetRFQ",
			Handler:    _RFQService_GetRFQ_Handler,
		},
		{
			MethodName: "ListRFQs",
			Handler:    _RFQService_ListRFQs_Handler,
		},
		{
			MethodName: "AddQuote",
			Handler:    _RFQService_AddQuote_Handler,
		},
		{
			MethodName: "ListQuotesForRFQ",
			Handler:    _RFQService_ListQuotesForRFQ_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _RFQService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rfq/v1/rfq.proto",
}
