// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: manufacturer/v1/manufacturer.proto

package manufacturerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manufacturer struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                       // MFR-YYYYMMDD-NNNN
	UserId      string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // soft ref to users(id), role=manufacturer; unique
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NameZh      string                 `protobuf:"bytes,4,opt,name=name_zh,json=nameZh,proto3" json:"name_zh,omitempty"`
	City        string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Country     string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"` // default "CN"
	Cluster     string                 `protobuf:"bytes,7,opt,name=cluster,proto3" json:"cluster,omitempty"` // Shenzhen | Dongguan | Huizhou | ...
	Description string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Website     string                 `protobuf:"bytes,9,opt,name=website,proto3" json:"website,omitempty"`
	// ---- PCB/PCBA capabilities (filterable) ----
	ServiceTypes    []string `protobuf:"bytes,10,rep,name=service_types,json=serviceTypes,proto3" json:"service_types,omitempty"`    // pcb_fab | pcba | cable_assembly | enclosure | box_build
	AssemblyTypes   []string `protobuf:"bytes,11,rep,name=assembly_types,json=assemblyTypes,proto3" json:"assembly_types,omitempty"` // smt | tht | mixed
	MinLayers       int32    `protobuf:"varint,12,opt,name=min_layers,json=minLayers,proto3" json:"min_layers,omitempty"`            // PCB layer count supported
	MaxLayers       int32    `protobuf:"varint,13,opt,name=max_layers,json=maxLayers,proto3" json:"max_layers,omitempty"`
	Materials       []string `protobuf:"bytes,14,rep,name=materials,proto3" json:"materials,omitempty"`                                     // fr4 | aluminum | rogers | flex | rigid_flex
	SurfaceFinishes []string `protobuf:"bytes,15,rep,name=surface_finishes,json=surfaceFinishes,proto3" json:"surface_finishes,omitempty"`  // hasl | enig | immersion_silver | osp
	MinOrderQty     int32    `protobuf:"varint,16,opt,name=min_order_qty,json=minOrderQty,proto3" json:"min_order_qty,omitempty"`           // MOQ (boards/units)
	MaxOrderQty     int32    `protobuf:"varint,17,opt,name=max_order_qty,json=maxOrderQty,proto3" json:"max_order_qty,omitempty"`           // 0 = unbounded
	LeadTimeDays    int32    `protobuf:"varint,18,opt,name=lead_time_days,json=leadTimeDays,proto3" json:"lead_time_days,omitempty"`        // typical prototype lead time
	MonthlyCapacity int32    `protobuf:"varint,19,opt,name=monthly_capacity,json=monthlyCapacity,proto3" json:"monthly_capacity,omitempty"` // boards/month
	SmallestPackage string   `protobuf:"bytes,20,opt,name=smallest_package,json=smallestPackage,proto3" json:"smallest_package,omitempty"`  // e.g. "0201" or "BGA 0.4mm pitch"
	Certifications  []string `protobuf:"bytes,21,rep,name=certifications,proto3" json:"certifications,omitempty"`                           // ISO9001 | IPC-A-610 | UL | RoHS | ISO13485
	// ---- trust / stats ----
	Verified      bool                   `protobuf:"varint,22,opt,name=verified,proto3" json:"verified,omitempty"`
	VerifiedAt    *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	Rating        float64                `protobuf:"fixed64,24,opt,name=rating,proto3" json:"rating,omitempty"` // 0..5
	OrderCount    int32                  `protobuf:"varint,25,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	OnTimeRate    float64                `protobuf:"fixed64,26,opt,name=on_time_rate,json=onTimeRate,proto3" json:"on_time_rate,omitempty"` // 0..100
	ContactEmail  string                 `protobuf:"bytes,27,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	ContactWechat string                 `protobuf:"bytes,28,opt,name=contact_wechat,json=contactWechat,proto3" json:"contact_wechat,omitempty"`
	Status        string                 `protobuf:"bytes,29,opt,name=status,proto3" json:"status,omitempty"` // active | pending | archived
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,30,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,31,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manufacturer) Reset() {
	*x = Manufacturer{}
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manufacturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manufacturer) ProtoMessage() {}

func (x *Manufacturer) ProtoReflect() protoreflect.Message {
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manufacturer.ProtoReflect.Descriptor instead.
func (*Manufacturer) Descriptor() ([]byte, []int) {
	return file_manufacturer_v1_manufacturer_proto_rawDescGZIP(), []int{0}
}

func (x *Manufacturer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manufacturer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Manufacturer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manufacturer) GetNameZh() string {
	if x != nil {
		return x.NameZh
	}
	return ""
}

func (x *Manufacturer) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Manufacturer) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Manufacturer) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Manufacturer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manufacturer) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Manufacturer) GetServiceTypes() []string {
	if x != nil {
		return x.ServiceTypes
	}
	return nil
}

func (x *Manufacturer) GetAssemblyTypes() []string {
	if x != nil {
		return x.AssemblyTypes
	}
	return nil
}

func (x *Manufacturer) GetMinLayers() int32 {
	if x != nil {
		return x.MinLayers
	}
	return 0
}

func (x *Manufacturer) GetMaxLayers() int32 {
	if x != nil {
		return x.MaxLayers
	}
	return 0
}

func (x *Manufacturer) GetMaterials() []string {
	if x != nil {
		return x.Materials
	}
	return nil
}

func (x *Manufacturer) GetSurfaceFinishes() []string {
	if x != nil {
		return x.SurfaceFinishes
	}
	return nil
}

func (x *Manufacturer) GetMinOrderQty() int32 {
	if x != nil {
		return x.MinOrderQty
	}
	return 0
}

func (x *Manufacturer) GetMaxOrderQty() int32 {
	if x != nil {
		return x.MaxOrderQty
	}
	return 0
}

func (x *Manufacturer) GetLeadTimeDays() int32 {
	if x != nil {
		return x.LeadTimeDays
	}
	return 0
}

func (x *Manufacturer) GetMonthlyCapacity() int32 {
	if x != nil {
		return x.MonthlyCapacity
	}
	return 0
}

func (x *Manufacturer) GetSmallestPackage() string {
	if x != nil {
		return x.SmallestPackage
	}
	return ""
}

func (x *Manufacturer) GetCertifications() []string {
	if x != nil {
		return x.Certifications
	}
	return nil
}

func (x *Manufacturer) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Manufacturer) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *Manufacturer) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Manufacturer) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *Manufacturer) GetOnTimeRate() float64 {
	if x != nil {
		return x.OnTimeRate
	}
	return 0
}

func (x *Manufacturer) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *Manufacturer) GetContactWechat() string {
	if x != nil {
		return x.ContactWechat
	}
	return ""
}

func (x *Manufacturer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Manufacturer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Manufacturer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateManufacturerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufacturer  *Manufacturer          `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"` // manufacturer.user_id is the actor (gateway-set); server assigns id/status/timestamps
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateManufacturerRequest) Reset() {
	*x = CreateManufacturerRequest{}
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManufacturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManufacturerRequest) ProtoMessage() {}

func (x *CreateManufacturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManufacturerRequest.ProtoReflect.Descriptor instead.
func (*CreateManufacturerRequest) Descriptor() ([]byte, []int) {
	return file_manufacturer_v1_manufacturer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateManufacturerRequest) GetManufacturer() *Manufacturer {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

type GetManufacturerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManufacturerRequest) Reset() {
	*x = GetManufacturerRequest{}
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManufacturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManufacturerRequest) ProtoMessage() {}

func (x *GetManufacturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManufacturerRequest.ProtoReflect.Descriptor instead.
func (*GetManufacturerRequest) Descriptor() ([]byte, []int) {
	return file_manufacturer_v1_manufacturer_proto_rawDescGZIP(), []int{2}
}

func (x *GetManufacturerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetManufacturerByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // a manufacturer fetching their own profile
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManufacturerByUserRequest) Reset() {
	*x = GetManufacturerByUserRequest{}
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManufacturerByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManufacturerByUserRequest) ProtoMessage() {}

func (x *GetManufacturerByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManufacturerByUserRequest.ProtoReflect.Descriptor instead.
func (*GetManufacturerByUserRequest) Descriptor() ([]byte, []int) {
	return file_manufacturer_v1_manufacturer_proto_rawDescGZIP(), []int{3}
}

func (x *GetManufacturerByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateManufacturerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufacturer  *Manufacturer          `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`      // by id
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // must equal the profile's user_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateManufacturerRequest) Reset() {
	*x = UpdateManufacturerRequest{}
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateManufacturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateManufacturerRequest) ProtoMessage() {}

func (x *UpdateManufacturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateManufacturerRequest.ProtoReflect.Descriptor instead.
func (*UpdateManufacturerRequest) Descriptor() ([]byte, []int) {
	return file_manufacturer_v1_manufacturer_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateManufacturerRequest) GetManufacturer() *Manufacturer {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *UpdateManufacturerRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

// Filters for browse + (later) capability matching. Empty fields = no filter.
type ListManufacturersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Cluster       string                 `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	ServiceType   string                 `protobuf:"bytes,4,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`    // matches if present in service_types
	AssemblyType  string                 `protobuf:"bytes,5,opt,name=assembly_type,json=assemblyType,proto3" json:"assembly_type,omitempty"` // matches if present in assembly_types
	Material      string                 `protobuf:"bytes,6,opt,name=material,proto3" json:"material,omitempty"`                             // matches if present in materials
	VerifiedOnly  bool                   `protobuf:"varint,7,opt,name=verified_only,json=verifiedOnly,proto3" json:"verified_only,omitempty"`
	MinLayersGte  int32                  `protobuf:"varint,8,opt,name=min_layers_gte,json=minLayersGte,proto3" json:"min_layers_gte,omitempty"` // manufacturer.max_layers >= this
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManufacturersRequest) Reset() {
	*x = ListManufacturersRequest{}
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManufacturersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManufacturersRequest) ProtoMessage() {}

func (x *ListManufacturersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManufacturersRequest.ProtoReflect.Descriptor instead.
func (*ListManufacturersRequest) Descriptor() ([]byte, []int) {
	return file_manufacturer_v1_manufacturer_proto_rawDescGZIP(), []int{5}
}

func (x *ListManufacturersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListManufacturersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListManufacturersRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ListManufacturersRequest) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ListManufacturersRequest) GetAssemblyType() string {
	if x != nil {
		return x.AssemblyType
	}
	return ""
}

func (x *ListManufacturersRequest) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

func (x *ListManufacturersRequest) GetVerifiedOnly() bool {
	if x != nil {
		return x.VerifiedOnly
	}
	return false
}

func (x *ListManufacturersRequest) GetMinLayersGte() int32 {
	if x != nil {
		return x.MinLayersGte
	}
	return 0
}

type ListManufacturersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufacturers []*Manufacturer        `protobuf:"bytes,1,rep,name=manufacturers,proto3" json:"manufacturers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManufacturersResponse) Reset() {
	*x = ListManufacturersResponse{}
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManufacturersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManufacturersResponse) ProtoMessage() {}

func (x *ListManufacturersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManufacturersResponse.ProtoReflect.Descriptor instead.
func (*ListManufacturersResponse) Descriptor() ([]byte, []int) {
	return file_manufacturer_v1_manufacturer_proto_rawDescGZIP(), []int{6}
}

func (x *ListManufacturersResponse) GetManufacturers() []*Manufacturer {
	if x != nil {
		return x.Manufacturers
	}
	return nil
}

func (x *ListManufacturersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type VerifyManufacturerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Verified      bool                   `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	ActorId       string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // admin (gateway enforces role=admin)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyManufacturerRequest) Reset() {
	*x = VerifyManufacturerRequest{}
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyManufacturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyManufacturerRequest) ProtoMessage() {}

func (x *VerifyManufacturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manufacturer_v1_manufacturer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyManufacturerRequest.ProtoReflect.Descriptor instead.
func (*VerifyManufacturerRequest) Descriptor() ([]byte, []int) {
	return file_manufacturer_v1_manufacturer_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyManufacturerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerifyManufacturerRequest) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerifyManufacturerRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

var File_manufacturer_v1_manufacturer_proto protoreflect.FileDescriptor

const file_manufacturer_v1_manufacturer_proto_rawDesc = "" +
	"\n" +
	"\"manufacturer/v1/manufacturer.proto\x12\x0fmanufacturer.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\b\n" +
	"\fManufacturer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\aname_zh\x18\x04 \x01(\tR\x06nameZh\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x18\n" +
	"\acluster\x18\a \x01(\tR\acluster\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x18\n" +
	"\awebsite\x18\t \x01(\tR\awebsite\x12#\n" +
	"\rservice_types\x18\n" +
	" \x03(\tR\fserviceTypes\x12%\n" +
	"\x0eassembly_types\x18\v \x03(\tR\rassemblyTypes\x12\x1d\n" +
	"\n" +
	"min_layers\x18\f \x01(\x05R\tminLayers\x12\x1d\n" +
	"\n" +
	"max_layers\x18\r \x01(\x05R\tmaxLayers\x12\x1c\n" +
	"\tmaterials\x18\x0e \x03(\tR\tmaterials\x12)\n" +
	"\x10surface_finishes\x18\x0f \x03(\tR\x0fsurfaceFinishes\x12\"\n" +
	"\rmin_order_qty\x18\x10 \x01(\x05R\vminOrderQty\x12\"\n" +
	"\rmax_order_qty\x18\x11 \x01(\x05R\vmaxOrderQty\x12$\n" +
	"\x0elead_time_days\x18\x12 \x01(\x05R\fleadTimeDays\x12)\n" +
	"\x10monthly_capacity\x18\x13 \x01(\x05R\x0fmonthlyCapacity\x12)\n" +
	"\x10smallest_package\x18\x14 \x01(\tR\x0fsmallestPackage\x12&\n" +
	"\x0ecertifications\x18\x15 \x03(\tR\x0ecertifications\x12\x1a\n" +
	"\bverified\x18\x16 \x01(\bR\bverified\x12;\n" +
	"\vverified_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x12\x16\n" +
	"\x06rating\x18\x18 \x01(\x01R\x06rating\x12\x1f\n" +
	"\vorder_count\x18\x19 \x01(\x05R\n" +
	"orderCount\x12 \n" +
	"\fon_time_rate\x18\x1a \x01(\x01R\n" +
	"onTimeRate\x12#\n" +
	"\rcontact_email\x18\x1b \x01(\tR\fcontactEmail\x12%\n" +
	"\x0econtact_wechat\x18\x1c \x01(\tR\rcontactWechat\x12\x16\n" +
	"\x06status\x18\x1d \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"^\n" +
	"\x19CreateManufacturerRequest\x12A\n" +
	"\fmanufacturer\x18\x01 \x01(\v2\x1d.manufacturer.v1.ManufacturerR\fmanufacturer\"(\n" +
	"\x16GetManufacturerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x1cGetManufacturerByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"y\n" +
	"\x19UpdateManufacturerRequest\x12A\n" +
	"\fmanufacturer\x18\x01 \x01(\v2\x1d.manufacturer.v1.ManufacturerR\fmanufacturer\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\"\x91\x02\n" +
	"\x18ListManufacturersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x18\n" +
	"\acluster\x18\x03 \x01(\tR\acluster\x12!\n" +
	"\fservice_type\x18\x04 \x01(\tR\vserviceType\x12#\n" +
	"\rassembly_type\x18\x05 \x01(\tR\fassemblyType\x12\x1a\n" +
	"\bmaterial\x18\x06 \x01(\tR\bmaterial\x12#\n" +
	"\rverified_only\x18\a \x01(\bR\fverifiedOnly\x12$\n" +
	"\x0emin_layers_gte\x18\b \x01(\x05R\fminLayersGte\"v\n" +
	"\x19ListManufacturersResponse\x12C\n" +
	"\rmanufacturers\x18\x01 \x03(\v2\x1d.manufacturer.v1.ManufacturerR\rmanufacturers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"b\n" +
	"\x19VerifyManufacturerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bverified\x18\x02 \x01(\bR\bverified\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId2\xa5\x05\n" +
	"\x13ManufacturerService\x12_\n" +
	"\x12CreateManufacturer\x12*.manufacturer.v1.CreateManufacturerRequest\x1a\x1d.manufacturer.v1.Manufacturer\x12Y\n" +
	"\x0fGetManufacturer\x12'.manufacturer.v1.GetManufacturerRequest\x1a\x1d.manufacturer.v1.Manufacturer\x12e\n" +
	"\x15GetManufacturerByUser\x12-.manufacturer.v1.GetManufacturerByUserRequest\x1a\x1d.manufacturer.v1.Manufacturer\x12_\n" +
	"\x12UpdateManufacturer\x12*.manufacturer.v1.UpdateManufacturerRequest\x1a\x1d.manufacturer.v1.Manufacturer\x12j\n" +
	"\x11ListManufacturers\x12).manufacturer.v1.ListManufacturersRequest\x1a*.manufacturer.v1.ListManufacturersResponse\x12_\n" +
	"\x12VerifyManufacturer\x12*.manufacturer.v1.VerifyManufacturerRequest\x1a\x1d.manufacturer.v1.Manufacturer\x12=\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBMZKgithub.com/nikitashilov/microblog_grpc/proto/manufacturer/v1;manufacturerv1b\x06proto3"

var (
	file_manufacturer_v1_manufacturer_proto_rawDescOnce sync.Once
	file_manufacturer_v1_manufacturer_proto_rawDescData []byte
)

func file_manufacturer_v1_manufacturer_proto_rawDescGZIP() []byte {
	file_manufacturer_v1_manufacturer_proto_rawDescOnce.Do(func() {
		file_manufacturer_v1_manufacturer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manufacturer_v1_manufacturer_proto_rawDesc), len(file_manufacturer_v1_manufacturer_proto_rawDesc)))
	})
	return file_manufacturer_v1_manufacturer_proto_rawDescData
}

var file_manufacturer_v1_manufacturer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_manufacturer_v1_manufacturer_proto_goTypes = []any{
	(*Manufacturer)(nil),                 // 0: manufacturer.v1.Manufacturer
	(*CreateManufacturerRequest)(nil),    // 1: manufacturer.v1.CreateManufacturerRequest
	(*GetManufacturerRequest)(nil),       // 2: manufacturer.v1.GetManufacturerRequest
	(*GetManufacturerByUserRequest)(nil), // 3: manufacturer.v1.GetManufacturerByUserRequest
	(*UpdateManufacturerRequest)(nil),    // 4: manufacturer.v1.UpdateManufacturerRequest
	(*ListManufacturersRequest)(nil),     // 5: manufacturer.v1.ListManufacturersRequest
	(*ListManufacturersResponse)(nil),    // 6: manufacturer.v1.ListManufacturersResponse
	(*VerifyManufacturerRequest)(nil),    // 7: manufacturer.v1.VerifyManufacturerRequest
	(*timestamppb.Timestamp)(nil),        // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 9: google.protobuf.Empty
}
var file_manufacturer_v1_manufacturer_proto_depIdxs = []int32{
	8,  // 0: manufacturer.v1.Manufacturer.verified_at:type_name -> google.protobuf.Timestamp
	8,  // 1: manufacturer.v1.Manufacturer.created_at:type_name -> google.protobuf.Timestamp
	8,  // 2: manufacturer.v1.Manufacturer.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: manufacturer.v1.CreateManufacturerRequest.manufacturer:type_name -> manufacturer.v1.Manufacturer
	0,  // 4: manufacturer.v1.UpdateManufacturerRequest.manufacturer:type_name -> manufacturer.v1.Manufacturer
	0,  // 5: manufacturer.v1.ListManufacturersResponse.manufacturers:type_name -> manufacturer.v1.Manufacturer
	1,  // 6: manufacturer.v1.ManufacturerService.CreateManufacturer:input_type -> manufacturer.v1.CreateManufacturerRequest
	2,  // 7: manufacturer.v1.ManufacturerService.GetManufacturer:input_type -> manufacturer.v1.GetManufacturerRequest
	3,  // 8: manufacturer.v1.ManufacturerService.GetManufacturerByUser:input_type -> manufacturer.v1.GetManufacturerByUserRequest
	4,  // 9: manufacturer.v1.ManufacturerService.UpdateManufacturer:input_type -> manufacturer.v1.UpdateManufacturerRequest
	5,  // 10: manufacturer.v1.ManufacturerService.ListManufacturers:input_type -> manufacturer.v1.ListManufacturersRequest
	7,  // 11: manufacturer.v1.ManufacturerService.VerifyManufacturer:input_type -> manufacturer.v1.VerifyManufacturerRequest
	9,  // 12: manufacturer.v1.ManufacturerService.HealthCheck:input_type -> google.protobuf.Empty
	0,  // 13: manufacturer.v1.ManufacturerService.CreateManufacturer:output_type -> manufacturer.v1.Manufacturer
	0,  // 14: manufacturer.v1.ManufacturerService.GetManufacturer:output_type -> manufacturer.v1.Manufacturer
	0,  // 15: manufacturer.v1.ManufacturerService.GetManufacturerByUser:output_type -> manufacturer.v1.Manufacturer
	0,  // 16: manufacturer.v1.ManufacturerService.UpdateManufacturer:output_type -> manufacturer.v1.Manufacturer
	6,  // 17: manufacturer.v1.ManufacturerService.ListManufacturers:output_type -> manufacturer.v1.ListManufacturersResponse
	0,  // 18: manufacturer.v1.ManufacturerService.VerifyManufacturer:output_type -> manufacturer.v1.Manufacturer
	9,  // 19: manufacturer.v1.ManufacturerService.HealthCheck:output_type -> google.protobuf.Empty
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_manufacturer_v1_manufacturer_proto_init() }
func file_manufacturer_v1_manufacturer_proto_init() {
	if File_manufacturer_v1_manufacturer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manufacturer_v1_manufacturer_proto_rawDesc), len(file_manufacturer_v1_manufacturer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manufacturer_v1_manufacturer_proto_goTypes,
		DependencyIndexes: file_manufacturer_v1_manufacturer_proto_depIdxs,
		MessageInfos:      file_manufacturer_v1_manufacturer_proto_msgTypes,
	}.Build()
	File_manufacturer_v1_manufacturer_proto = out.File
	file_manufacturer_v1_manufacturer_proto_goTypes = nil
	file_manufacturer_v1_manufacturer_proto_depIdxs = nil
}
